### ISSUE TITLE
Test failure: tests/effects/test6 fails

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#105]

**Comment by dhil** [comment]
Test6 seems to work fine on my end. I expect this issue has been fixed a while ago. I suppose this issue could be closed.

**Comment by stedolan** [comment]
test6 works fine on bytecode, but does something stupid on native code.

**Comment by dhil** [comment]
With the native compiler I get
```
$ ocaml -version
The OCaml toplevel, version 4.02.2+multicore-dev0
$ ocamlopt test6.ml -o a.out
$ ./a.out
true
true
$ echo $?
0
$ cat test6.reference
true
true
```
Isn't that the expected behaviour?

**Comment by kayceesrk** [comment]
Is this with default handlers patch?

**Comment by dhil** [comment]
> Is this with default handlers patch?
Yes.

**Comment by kayceesrk** [comment]
I could believe that with default handlers, the issue goes away. In that case, once the default handlers PR #123 is merged, we should close the issue.

**Comment by stedolan** [comment]
For reference, on trunk it does this:
```
~/projects/ocaml-multicore$ ./ocamlopt testsuite/tests/effects/test6.ml -o test6
~/projects/ocaml-multicore$ ./test6
true
Fatal error: exception Unhandled
```
Looking forward to being able to close this!
