### ISSUE TITLE
Incorrect location in bytecode backtrace

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#108]
Bytecode backtraces reports wrong location for `perform`. See `tests/backtrace/backtrace_effects.ml`. Native code produces the correct result. To reproduce run `make one DIR=tests/backtrace` in `testsuite` directory.

**Comment by stedolan** [comment]
This is fixed. (For a while now, not sure exactly when this test started passing).

**Comment by kayceesrk** [comment]
> not sure exactly when this test started passing

possibly after the fiber refactoring.
