### ISSUE TITLE
Segmentation fault with Thread

### ISSUE THREAD

**Issue by fondation451** [ocamllabs/ocaml-multicore#112]
I have segmentation fault when I'm using threads although I haven't when I'm not using it. Maybe, I have not used them correctly. Here is the test file : https://github.com/fondation451/kcas/blob/master/src/kcas_lf.ml

**Comment by stedolan** [comment]
Ah, you're using OCaml's Threads module, which doesn't work on multicore (oddly enough!).

`Threads` is the interface to OCaml's globally-locked threads, which never run in parallel (and code using `Threads` relies on this). The interface to multicore's actually-parallel threads is in `Domain`:

    Domain.create (fun () -> thread1 (a1, a2))

[We don't have Domain.join yet](https://github.com/ocamllabs/ocaml-multicore/issues/89), but you can just use `Unix.sleep` for hacky testing. (Domain.join will arrive soon)

**Comment by hakuch** [comment]
Out of curiosity, do you envision the `Thread` module being adapted to work on multicore (perhaps while still being globally locked), or removing it from the standard library entirely?

**Comment by stedolan** [comment]
Adapted, because there's plenty of code that depends on it (see #100). It will probably have to be globally locked, because there's plenty of code using `Thread` which assumes that threads never run in parallel.
