### ISSUE TITLE
Is non-spurious compare_and_swap possible?

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#115]
I would like to expose a `compare_and_swap : 'a t -> 'a -> 'a -> 'a` primitive in the atomics library [0], with the following semantics:

```ocaml
(* atomically *)
let compare_and_swap r v1 v2 =
  let oldv = !r in
  if oldv = v1 then r := v2;
  oldv
```

The implementation of this primitive would be:

```C
CAMLexport value caml_atomic_cas_field_val (value obj, value oldval, value newval)
{
  value* p = &Op_val(obj)[0];
  value out;

  if (Is_young(obj)) {
    /* non-atomic CAS since only this thread can access the object */
    out = *p; 
    if (*p == oldval) {
      *p = newval;
      write_barrier(obj, field, oldval, newval);
    } 
    return out;
  } else {
    /* need a real CAS */
    out = __sync_val_compare_and_swap(p, oldval, newval);
    if (out == oldval)
      write_barrier(obj, field, oldval, newval);
    else {
      /* Tricky case
      Assert (!Is_block(out) || !Is_foreign(out)); might fail since out might be foreign. 
      out = caml_read_barrier (obj, field); is not the right solution since we are reading the value again.
      This can be spurious. */
    }   
    return out;
  }
}
```

If the real CAS fails, then the `out` value might be foreign. Invoking the read barrier might return spurious results since the ref might have been overwritten since.

[0] https://github.com/ocamllabs/ocaml-multicore/pull/109

**Comment by stedolan** [comment]
Hmm. I think the correct implementation is to invoke the read barrier, but loop until you get either a value not equal to oldval or a successful CAS, something like (uncompiled and untested...):

    value found;
    int success = 0;
    do {
      found = __sync_val_compare_and_swap(p, oldval, newval);
      if (found == oldval) {
        success = 1;
        write_barrier(obj, field, oldval, newval);
      } else {
        if (Is_foreign(found)) found = caml_read_barrier(obj, field);
      }
    } while (!success && found == oldval);
    return found;

On the other hand, I'm not sure why this loop needs to be in C.

**Comment by kayceesrk** [comment]
I had ended up with a similar solution. The loop is undesirable though. Do you have an idea of whether we could get away with only exposing `compare_and_set`? C++ only exposes this if I am not mistaken: http://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange.

**Comment by stedolan** [comment]
I would be happy with just `compare_and_set`.

As usual, C++ exposes all possible features: `atomic_compare_exchange_foo` takes the old value as a pointer, and modifies it if a different value was found.
