### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by bluddy** [ocamllabs/ocaml-multicore#116]
It would be very useful, I think, to create a Roadmap indicating what is required to attain release-quality level on this feature (and frankly, on every other major feature). Too often it appears like an OCaml feature is languishing. The status of the project is completely unknown to an external visitor such as myself: how well does multicore appear to work now? How comprehensive are the tests? How good is the OSX support?

A Roadmap would inform visitors about the current status of the project and allow particularly enthusiastic visitors to direct their efforts in a productive manner. See example roadmap [here](https://neovim.io/roadmap/). A wiki would perhaps be better than an actual github site for something like this, where it's not an independent project.

**Comment by kayceesrk** [comment]
See https://github.com/ocamllabs/ocaml-multicore/projects. Instead of a separate wiki/site, I'd like to track the work items as issues as they are actionable and track provenance.

**Comment by bluddy** [comment]
Wow. Didn't even know this was possible in github. Sweet.
