### ISSUE TITLE
Allocator structs implementation (in-memory metadata carving)

### ISSUE THREAD

**Issue by hpliotas** [ocamllabs/ocaml-multicore#121]
Hi, is there any interest to (1) experimenting with different carving strategies for allocator metadata, possibly avoiding using linked lists (2) take advantage of the fact that memory chuck sizes are not arbitrary like in a normal C program (effectively leading to application specific garbage collectors) (3) experimenting with different synchronization schemas for multithreaded applications (there are quite a few alternatives other than Streamflow to look for ideas...)

**Comment by stedolan** [comment]
In general, yes, although we have lots of other aspects to optimise as well. If you have some concrete proposals, I'd like to hear them, though!

(1) I'm not sure what benefit we'd get from avoiding using linked lists - the current allocator never traverses a linked list.

(2) I don't really follow this. What extra information do we have, and how do you suggest we take advantage of it?

(3) Do you have a specific suggestion? There's very little synchronization in the allocator at the moment, so I'm not sure if there's much to win here.

**Comment by hpliotas** [comment]
Hi, thx for the quick response!

(1) I did not mention list traversing. "Placing" free chunks (placing is in brackets become its semantics wrt to true memory layout are different if the implementation is an in-memory carved list or bitmap or raw-pointer bookeeping or something else) of memory on top of a stack can becoming beneficial when actual cached memory is used in subsequent allocations. In other scenarios that may not be the case

(2) If the size of allocations is somehow known at compile time, it could be used as an advantage (ie reduce internal fragmentation for fixed size buckets)

(3) This is just a question -> is there is indeed a severe contention issue on the allocator (or performance problems due to unintentional allocator-induced false sharing and so on...)

This is not a proposal. I was wondering if there is an active interest on the allocator implementation because I am looking for a nice side-project :)

**Comment by stedolan** [comment]
(1) The allocator does try to ensure that the next page of objects allocated from is the last one swept. Be aware that this aspect is quite different in a GC'd setting than in a malloc / free implementation, because sweeping (a) happens in batch, not one object at a time like free() and (b) can be guaranteed to be done by the thread that allocated the memory.

(2) The shared heap allocator mostly only comes into play for blocks which survive a minor collection. (On the minor heap, blocks are bump-allocated). At that point, we don't have any static information about sizes.

(3) The allocator has very little contention. Allocator-induced false sharing is possible, though.

The shared heap allocator lives in `byterun/shared_heap.c` if you want to take a look.

**Comment by hpliotas** [comment]
Hmm, nice! How do you test any GC code changes? (both for performance and correctness)

**Comment by kayceesrk** [comment]
For correctness, heap verification is enabled in debug mode. When configuring, use `-with-debug-runtime` and when compiling programs you can use `-runtime-variant d` to select the debug runtime. We don't yet have a standard set of benchmarks for the GC.

**Comment by hpliotas** [comment]
Ocamlopt appears to be emitting native code (so GC's *C* code can be profiled and examined easily with perf on linux). Is there something like an open source ocaml app that (1) is heavy on the GC (I suspect this happens anyway) (2) uses some kind of shared address space multithreading, perhaps some kind of ocaml-layer threading abstraction that ultimately boils down to pthreads...?

**Comment by kayceesrk** [comment]
Well-written OCaml apps tend to be not heavy on GC. That said, for (2), take a look at https://github.com/facebook/hhvm/tree/master/hphp/hack. I suspect hack will also satisfy (1).

**Comment by hpliotas** [comment]
Hello again! Other than Real World Ocaml and this (https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html) (both are great) are there any other good references on ocaml internals? I was looking for something like this one https://www.slideshare.net/HyungChulPark/ocaml-internal in English...

**Comment by kayceesrk** [comment]
> are there any other good references on ocaml internals?

Nothing particularly comes to mind. Happy to answer any specific questions at https://discuss.ocaml.org/t/about-multicore/138. 

>  https://www.slideshare.net/HyungChulPark/ocaml-internal

I learnt a lot about multicore internals from a Google translated version of the same :-)

**Comment by stedolan** [comment]
I'm not sure if there's an actual issue here, so I'm closing this (but feel free to reopen). For general discussion, we hang around on https://discuss.ocaml.org.
