### ISSUE TITLE
Test `tests/lib-dynlink-native` fails on master

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#133]
The error message is `Failure: Serializing closures is broken`. Not sure what changed to make this test fail only now. @stedolan thoughts?

**Comment by stedolan** [comment]
That test has failed for a long time. It's [disabled in the CI builds](https://github.com/ocamllabs/ocaml-multicore/blob/master/testsuite/disabled#L16), and there's an issue about fixing closure serialisation: #75

**Comment by kayceesrk** [comment]
My bad. I was not reading the error long properly:

```
Running tests from 'tests/lib-dynlink-native' ...
/home/travis/build/ocamllabs/ocaml-multicore/testsuite/../otherlibs/systhreads/libthreadsnat.a(st_stubs_n.o): In function `caml_thread_new_info':
/home/travis/build/ocamllabs/ocaml-multicore/otherlibs/systhreads/st_stubs.c:225: undefined reference to `caml_alloc_main_stack'
```
I'd made `caml_alloc_main_stack` static, which caused the test to fail on compilation. CI running now and I expect this to pass: https://travis-ci.org/ocamllabs/ocaml-multicore/builds/234120177.
