### ISSUE TITLE
GC Seg Fault

### ISSUE THREAD

**Issue by fondation451** [ocamllabs/ocaml-multicore#138]
Hello,

I have been through GC segmentation fault while developing lock-free data structure. It appears to be a segmentation fault of the Garbage Collector in the mark_normalize function.

To reproduce the segmentation fault, you need to install my library using opam :
git clone https://github.com/fondation451/kcas
cd kcas
opam pin add kcas .
cd ..
git clone https://github.com/fondation451/lockfree
cd lockfree
opam pin add lockfree
cd ..
git clone https://github.com/fondation451/reagents
cd reagents
make

The executable is in reagents directory, it is _build/example/hash_test.native

To reproduce the segmentation fault, you use this command :
_build/examples/hash_test.native 10 10000

It does not appear every time, so this executable is a loop. It might take some time before showing up or it can show up right away.

Thank you for your help
Nicolas

**Comment by alexeyshch** [comment]
It's probably fixed now, see #137.

**Comment by kayceesrk** [comment]
@fondation451 can you check if the bug is gone?

**Comment by kayceesrk** [comment]
This bug has been fixed.
