### ISSUE TITLE
Rebase to latest stable OCaml version

### ISSUE THREAD

**Issue by bluddy** [ocamllabs/ocaml-multicore#140]
One reason I think people in the community may hesitate to experiment with multicore OCaml (aside from not being aware of it) is that it's several versions behind OCaml's current version. I think it would help to update to a new version of OCaml, especially since this is such a long-running project.

Are there any known technical issues with regard to doing this?

**Comment by stedolan** [comment]
Nope, it's just some work that needs doing. In fact, this is issue #37.

**Comment by bluddy** [comment]
Thanks -- couldn't find that one.
