### ISSUE TITLE
Possible false sharing with global atomics

### ISSUE THREAD

**Issue by stedolan** [ocamllabs/ocaml-multicore#155]
There are a few `atomic_uintnat`s around, which may profit from explicit padding to ensure they don't share cache lines. Benchmarking needed.

**Comment by bluddy** [comment]
Important to bear in mind: even if this is found to have no impact now, it can cause issues later on when memory layout is perturbed in some manner.

**Comment by stedolan** [comment]
I don't think keeping this issue open is terribly useful. If false sharing shows up in profiling, we'll fix it, but so far it hasn't been an issue.
