### ISSUE TITLE
`make -j world` fails intermittently

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#16]
`make -j world` works fine on the vanilla OCaml.

**Comment by stedolan** [comment]
What error do you get?

**Comment by kayceesrk** [comment]
../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -warn-error A -w L -w R -w Z -I ../otherlibs/unix -safe-string -c ocamlbuild_plugin.mli
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -warn-error A -w L -w R -w Z -I ../otherlibs/unix -safe-string -c ocamlbuild_executor.mli
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -warn-error A -w L -w R -w Z -I ../otherlibs/unix -safe-string -c ocamlbuild_unix_plugin.mli
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -warn-error A -w L -w R -w Z -I ../otherlibs/unix -safe-string -c ocamlbuild.ml
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -warn-error A -w L -w R -w Z -I ../otherlibs/unix -safe-string -c ocamlbuild_executor.ml
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -warn-error A -w L -w R -w Z -I ../otherlibs/unix -safe-string -c ocamlbuild_unix_plugin.ml
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -warn-error A -w L -w R -w Z -I ../otherlibs/unix -safe-string -c ocamlbuild_plugin.ml
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -pp './remove_DEBUG' -I ../parsing -I ../utils -I ../typing -I ../driver -I ../bytecomp -I ../tools -I ../toplevel/ -I ../stdlib -I ../otherlibs/str -I ../otherlibs/dynlink -I ../otherlibs/unix -I ../otherlibs/num -I ../otherlibs/graph -warn-error A -safe-string -c odoc_latex.ml
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -I ../otherlibs/unix -o ocamlbuild.byte \
          unix.cma ocamlbuild_pack.cmo ocamlbuild_plugin.cmo ocamlbuild_executor.cmo ocamlbuild_unix_plugin.cmo ocamlbuild.cmo
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -pp './remove_DEBUG' -I ../parsing -I ../utils -I ../typing -I ../driver -I ../bytecomp -I ../tools -I ../toplevel/ -I ../stdlib -I ../otherlibs/str -I ../otherlibs/dynlink -I ../otherlibs/unix -I ../otherlibs/num -I ../otherlibs/graph -warn-error A -safe-string -c odoc_texi.ml
    ../boot/ocamlrun ../ocamlc -nostdlib -I ../stdlib -a -o ocamlbuildlib.cma \
          ocamlbuild_pack.cmo ocamlbuild_plugin.cmo ocamlbuild_executor.cmo ocamlbuild_unix_plugin.cmo
    File "_none_", line 1:
    Error: Files ocamlbuild_plugin.cmo and ocamlbuild_pack.cmo
       make inconsistent assumptions over interface Ocamlbuild_pack
    make[3]: *** [ocamlbuildlib.cma] Error 2
    make[3]: *** Waiting for unfinished jobs....
    File "_none_", line 1:
    Error: Files ocamlbuild_plugin.cmo and ocamlbuild_pack.cmo
       make inconsistent assumptions over interface Ocamlbuild_pack
    make[3]: *** [ocamlbuild.byte] Error 2
    make[2]: *** [ocamlbuild.byte] Error 2
    make[2]: *** Waiting for unfinished jobs....
    .....
    .....
    make[1]: *** [all] Error 2
    make: *** [world] Error 2

**Comment by stedolan** [comment]
This was fixed by 4e316f9d8904d9c8589d524a3c4aae2474868d38, so the issue went away when we merged with 4.02.2
