### ISSUE TITLE
tests/parallel/timing.ml fails in CI

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#164]
[`tests/parallel/timing.ml`](https://github.com/ocamllabs/ocaml-multicore/blob/master/testsuite/tests/parallel/timing.ml) [fails in the CI](https://travis-ci.org/ocamllabs/ocaml-multicore/jobs/316675715). The test mentions that it might fail in a heavily loaded system. Is this failure expected?

**Comment by stedolan** [comment]
It is, sadly! We should adjust the `step` parameter in the test to fix this.

**Comment by stedolan** [comment]
Fixed by 48e8ae8, I think. Reopen if timing fails again.

**Comment by stedolan** [comment]
Actually fixed (?) by c499553
