### ISSUE TITLE
local effect definitions

### ISSUE THREAD

**Issue by yallop** [ocamllabs/ocaml-multicore#171]
I'm not sure whether this fits with the long-term plans for effects.  But now that this repository is up-to-date with `trunk`, it would be useful to have local effect definitions, analogous to local exceptions (https://github.com/ocaml/ocaml/pull/301):

```ocaml
let effect E : t in e
```

In polymorphic functions it's often useful to have effects that depend on local type names, like this:

```ocaml
let f (type a) ... =
   let effect E : a in
   ...
```

At present these have to be written using local modules

```ocaml
let f (type a) ... =
   let module M = struct effect E : a end in
   ...
```

**Comment by stedolan** [comment]
Local effect definitions are definitely useful, but we're not going to add them here. Work on the surface syntax for effects is mostly being done by @lpw25 these days on his typed effects branch, and we're trying to have less non-OCaml-trunk syntax rather than more in this repo.
