### ISSUE TITLE
[Native backend] SP should be pointer and not offset

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#183]
The stack pointer stored in the fiber data structure is an offset from the top of the stack (https://github.com/ocamllabs/ocaml-multicore/blob/master/byterun/caml/fiber.h#L66). This design is great for portability since the stack pointer need not be updated when the fiber is moved to a different part of the heap. 

However, this does mean that we will have to perform the computation to go from pointer to offset and vice versa when switching between fibers or performing C calls. This complicates the code in the <arch>.s files (for example, https://github.com/ocamllabs/ocaml-multicore/blob/master/asmrun/amd64.S#L173-L179 and also DWARF for stack unwinding: https://github.com/ocamllabs/ocaml-multicore/blob/master/asmrun/amd64.S#L454-L459). 

Instead, the SP field should store the pointer into the fiber data structure that corresponds to the stack pointer. This simplifies all of the cases previously mentioned. Care must be taken to rewrite the pointer when the fiber is moved during a GC.

**Comment by stedolan** [comment]
Fixed by #209
