### ISSUE TITLE
[Native backend] Exception pointers in trap frames should be offsets from previous trap frames

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#184]
Exception pointers are represented as offsets from stack high. Hence, in order to calculate the exception pointer, we need to compute the stack high (See https://github.com/ocamllabs/ocaml-multicore/blob/master/asmcomp/amd64/emit.mlp#L964-L972). Instead, if the exception pointer were represented as offsets from the previous trap frame, which is readily available (in r14 on amd64), then pushing a new trap frame become simpler.

This is best implemented along with #182.

**Comment by stedolan** [comment]
Done in #215
