### ISSUE TITLE
Enforce the memory model

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#186]
[Multicore OCaml's memory model](http://kcsrk.info/papers/pldi18-memory.pdf) is free on `amd64` but requires fence (`dmb ld`) before stores on arm64. This requires fence insertion in the following places:

- [ ] In aarch64/emit.mlp, before `IStore` instructions if it is an assignment (as opposed to initialising store).
- [ ] In the write barrier `caml_modify` before the store. 

We also need a full fence:

- [ ] At the end of a minor GC
- [ ] After promotion
- [ ] After initialising globals
- [ ] After `caml_alloc_shr`

Our current focus in `amd64` and `aarch64` backends only. 

Currently, we only focus on `amd64` and `arm64` backends.

**Comment by stedolan** [comment]
Most of this was fixed by #225. Moved a few ARM-specific bits to #86
