### ISSUE TITLE
there is no uninstall target in Makefile

### ISSUE THREAD

**Issue by mprevot** [ocamllabs/ocaml-multicore#190]
So far, in today's repository. This would be useful.

> sudo make uninstall
> make: *** No rule to make target 'uninstall'.  Stop.

**Comment by stedolan** [comment]
We haven't modified the install system at all, so if you want this fixed you're best off reporting it to the upstream OCaml bug tracker at https://caml.inria.fr/mantis.

As a workaround, I usually install into a dedicated directory (`./configure -prefix /foo/bar/baz`), which can be deleted in its entirety.
