### ISSUE TITLE
Avoid rescanning fibers after minor GC

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#193]
The interaction between mutator and GC access of fibers requires atomic synchronisation: https://github.com/ocamllabs/ocaml-multicore/issues/41. See `fiber.c` for the current implementation. The states are `FIBER_CLEAN`, `FIBER_SCANNING` or some domain indicating that the fiber might have pointers into that domain's minor heap. From the major GC pov, there is no distinction between `Grey` and `Black` -- after a minor GC, the fiber status goes back to `FIBER_CLEAN` and is scanned again before switching to that fiber. This should be avoided. 

A new state, `FIBER_SCANNED` should be added. The major GC marking now does `FIBER_CLEAN --> FIBER_SCANNING --> FIBER_SCANNED`. Before context switching to a fiber, the mutator might either go `FIBER_CLEAN --> FIBER_SCANNING --> domain*` or `FIBER_SCANNED --> domain*`. The minor GC now goes `domain* -> FIBER_SCANNED`. The only issue now is that at the end of a major GC, we need all of the fibers to go to `FIBER_CLEAN` from `FIBER_SCANNED` (every reachable one is now in this state). We can reuse the trick with the mark colour to flip the meaning of `FIBER_CLEAN` and `FIBER_SCANNED` at the end of the major cycle.

**Comment by stedolan** [comment]
Fixed by #203. Instead of adding `FIBER_SCANNED`, all of the fiber states were deleted and the fiber's status is indicated instead by the GC state of its continuation.
