### ISSUE TITLE
The latest two commits brokes the build

### ISSUE THREAD

**Issue by senyan** [ocamllabs/ocaml-multicore#2]
`` cbb60bb1689601f6fe0f782f046330b4bea51337`` and ``a36d7ae41ff0099aa409476cfce960a458dff1ae`` actually brokes the build. It was complaining about lack of ``minor_heap.h``.

**Comment by lpw25** [comment]
.depends file was out of date. This was fixed by https://github.com/ocamllabs/ocaml-multicore/commit/4b314e0b1cff8e5c84de12b7e61d4a214963c110

**Comment by senyan** [comment]
Cool.  I
