### ISSUE TITLE
opam install failure of 4.06.1+multicore

### ISSUE THREAD

**Issue by houndofsound** [ocamllabs/ocaml-multicore#228]
I have a raspberry 3/raspbian.

it's failing on an alignment check:

<code>
make[1]: Entering directory '/home/dev/.opam/4.06.1+multicore/.opam-switch/build/ocaml-variants.4.06.1+multicore/byterun'
echo "/home/dev/.opam/4.06.1+multicore/lib/ocaml/stublibs" > ld.conf
echo "/home/dev/.opam/4.06.1+multicore/lib/ocaml" >> ld.conf
sed -n -e '/^  /s/ \([A-Z]\)/ \&\&lbl_\1/gp' \
       -e '/^}/q' caml/instruct.h > caml/jumptbl.h
gcc -c -O2 -fno-strict-aliasing -fwrapv -Wall  -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  interp.c
In file included from caml/alloc.h:21:0,
                 from interp.c:20:
caml/misc.h:119:16: error: size of array ‘static_assertion_failure_line_50’ is negative
   typedef char static_assertion_failure_line_##l[(b) ? 1 : -1]
                ^
caml/misc.h:120:36: note: in expansion of macro ‘CAML_STATIC_ASSERT_3’
 #define CAML_STATIC_ASSERT_2(b, l) CAML_STATIC_ASSERT_3(b, l)
                                    ^~~~~~~~~~~~~~~~~~~~
caml/misc.h:121:31: note: in expansion of macro ‘CAML_STATIC_ASSERT_2’
 #define CAML_STATIC_ASSERT(b) CAML_STATIC_ASSERT_2(b, __LINE__)
                               ^~~~~~~~~~~~~~~~~~~~
caml/domain_state.h:44:1: note: in expansion of macro ‘CAML_STATIC_ASSERT’
 CAML_STATIC_ASSERT(
 ^~~~~~~~~~~~~~~~~~
Makefile:207: recipe for target 'interp.o' failed
make[1]: *** [interp.o] Error 1
make[1]: Leaving directory '/home/dev/.opam/4.06.1+multicore/.opam-switch/build/ocaml-variants.4.06.1+multicore/byterun'
Makefile:391: recipe for target 'coldstart' failed
make: *** [coldstart] Error 2
/home/dev/.opam/log/ocaml-variants

**Comment by houndofsound** [comment]
the <> button didn't work so |I put <code> in front but that seems to have removed all newlines.
I cannot get the Edit button to respond either....

**Comment by houndofsound** [comment]
Not supported!
I was deceived by the readme.md which lists ARM but is of course the original distro file.

**Comment by stedolan** [comment]
Ah right, we should update the README or at least point out that it's not accurate for multicore.

ARM64 was supported before, and will be again once we fix the build (see #86). It looks like you were trying to build on ARM32, though, which multicore has never supported. (We'll get around to it eventually, but it's not a priority for the moment).
