### ISSUE TITLE
Should `verify_swept` be DEBUG only?

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#28]
`caml_sweep` invokes `verify_swept` [1]. But the name suggests that it should only be invoked when debugging.

[1] https://github.com/ocamllabs/ocaml-multicore/blob/master/byterun/shared_heap.c#L352

**Comment by stedolan** [comment]
Correct, it need not be run in non-debug builds. I found it convenient to
leave it on, since it does not cause much overhead and the log messages it
generates are informative.

**Comment by kayceesrk** [comment]
Fixed f6fd9cff44d410f1c11fe8ef9635bb6acd38eef6
