### ISSUE TITLE
Gc.print_stat segfaults

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#29]
```
# Gc.print_stat stdout;;
Segmentation fault: 11
```

It is quite possible that `print_stat` hasn't been updated to work with multicore.

**Comment by stedolan** [comment]
Most of the gc_ctrl functions are stubs at the moment, returning unit even
when unit is not the right type.

Some API changes may be necessary to fix these; it's not clear that the
same settings make sense with the new GC.
