### ISSUE TITLE
Domain.Sync.cpu_relax should poll for interrupts without locking

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#348]
`Domain.Sync.cpu_relax` will call the C function `caml_ml_domain_cpu_relax`. This function checks for incoming interrupts before calling `cpu_relax`. This is done by obtaining and releasing the domain lock. 

https://github.com/ocaml-multicore/ocaml-multicore/blob/172fe18bbc7fcdaa1fc286869c28a2c59ecbf27a/runtime/domain.c#L1298-L1300

This will interfere with the domain that is attempting to interrupt this domain. It would be better to poll for interrupt without the lock and if there happens to be an interrupt waiting, then we handle the interrupt with lock. 

In the polling version, we may need to load `s->qhead` using c11 atomics? 

https://github.com/ocaml-multicore/ocaml-multicore/blob/172fe18bbc7fcdaa1fc286869c28a2c59ecbf27a/runtime/domain.c#L944

What is the interaction between a store in a critical section protected by a lock and a load? Which version of `atomic_load` do I want? 

https://github.com/ocaml-multicore/ocaml-multicore/blob/172fe18bbc7fcdaa1fc286869c28a2c59ecbf27a/runtime/caml/camlatomic.h#L37-L38

**Comment by stedolan** [comment]
I think `if (Caml_check_gc_interrupt(Caml_state)) { lock; handle_interrupts; unlock }` is what you want.
