### ISSUE TITLE
Add `Gc.promote` to explicitly promote objects to the major heap.

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#36]
`Gc.promote : 'a -> unit` exposes the ability to explicitly perform promotions. In move-based promotion, promoting recently allocated objects is cheaper than promoting older objects since a smaller part of the young heap needs to be scanned in the former case. The behavior of `Gc.promote x` is the following:
- if `x` is a primitive or a major heap object, then `Gc.promote x` is a noop.
- if `x` is a young object, then `x` (and its transitive closure) is promoted to the major heap. 

Since promotion needs to forward all reference to promoted objects, `Gc.promote` must be a safe-point where all the roots are visible to the GC. This must be explicitly ensured by the C bindings.

**Comment by avsm** [comment]
is it useful to expose the two options via a `bool` return value?  (i.e. If a promotion actually occurs, return true).  Would still be a non-allocating function.

**Comment by kayceesrk** [comment]
Sure. Do you have a use-case in mind for the return value?

**Comment by kayceesrk** [comment]
As per @stedolan's suggestion, the better API is `Gc.promote value target`, which promotes `value` iff `value` is young and `target` is in major heap. For example, before pushing a value `x` to a `queue`, `Gc.promote x queue` would be invoked, which promotes `x` if `queue` is shared. This is better than unconditional promotion.
