### ISSUE TITLE
Promote to OCaml trunk

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#37]
Multicore OCaml is currently based off of vanilla OCaml 4.02.1. The compiler needs to be merged with OCaml 4.03.

**Comment by kayceesrk** [comment]
As a first step, here is a PR promoting to 4.02.2 https://github.com/ocamllabs/ocaml-multicore/pull/52.

**Comment by dhil** [comment]
April 11, 2016 is some time ago now. I suppose we would like to bring the compiler up to 4.05 now. However, would you do that step-wise, i.e. bring it up to 4.03 first, then 4.04, or go directly to 4.05?

**Comment by bluddy** [comment]
I was also wondering this. Seems to me like ripping off that band-aid and going straight to 4.05 might be best, but I could be wrong.

**Comment by kayceesrk** [comment]
Moving up to latest releases version would be the target. If promoting up
all the way is tricky, then I'd try older versions.

**Comment by dhil** [comment]
I am willing to try to bring the compiler up to the latest release. Previous experience tells me it is fix the merge conflicts in the compiler itself, the difficult parts are the runtime bits. I am not too familiar with the new runtime, in particular, the garbage collector, so I am going to need some assistance for those bits.

I could start this after ICFP.

**Comment by kayceesrk** [comment]
Great @dhil. Happy to help you with the runtime bits of merging.

**Comment by sidkshatriya** [comment]
Effects/Multicore through effects in OCaml are a really exciting and elegant proposed addition! I've been reading the various resources on @kayceesrk's blog. Some of the examples on https://github.com/kayceesrk/effects-examples are quite mind blowing. Kudos!  

While incorporation into OCaml proper is probably quite a ways off, I do think that it would be great idea to promote this to 4.05! It will give people more confidence to start using this.

**Comment by bluddy** [comment]
@dhil, are you working on this? It's something I could work on in my spare time, but I wouldn't want to duplicate efforts.

**Comment by dhil** [comment]
Well, not actively at the moment. @kayceesrk and I agreed during ICFP for me to work on something else. 

Bonus info; I spoke with Damien Doligez during ICFP regarding the release of OCaml 4.06. He told me that the feature freeze was imminent, and hopefully the release happens within the next 6 months. Thus it may be worth going to targeting 4.06.

**Comment by bluddy** [comment]
OK. So I can do this in my spare time.

> Bonus info; I spoke with Damien Doligez during ICFP regarding the release of OCaml 4.06. He told me that the feature freeze was imminent, and hopefully the release happens within the next 6 months. Thus it may be worth going to targeting 4.06.

Good point. Feature freeze for 4.06 was last Friday.

**Comment by kayceesrk** [comment]
See #167. WIP to promote to 4.06.0.

**Comment by kayceesrk** [comment]
Caught up to 4.06.1!
