### ISSUE TITLE
Parallel domain unsound functions in stdlib

### ISSUE THREAD

**Issue by ctk21** [ocamllabs/ocaml-multicore#376]
We have functions in stdlib which can be unsound when two domains use the function at the same time.

For example, `Random.bits ()` currently uses a global state that is shared by multiple domains that is [updated non-atomically](https://github.com/ocaml-multicore/ocaml-multicore/blob/4.10.0/stdlib/random.ml#L76-L83). This makes the function potentially not safe to use with multiple domains (in this case different state sequences could be observed between a sequential program and a parallel one. Imagine one domain suspended (by OS, CPU, etc) after calculating its local `(s.idx + 1) mod 55` on L77 but before storing it to `s.idx` and another domain then executing the whole function from scratch).

One strategy for handling this issue is to sweep the stdlib documentation and flag all functions that are unsafe for multiple domains to use.

**Comment by ctk21** [comment]
We also need to be careful with the usage of `lazy`. Stdlib makes use of lazy in places like `Hashtbl.create` and `Filename.temp_file` which can also be a source of unexpected behaviour between domains. The lazy forcing itself could raise `RacyLazy` which could be unexpected.

**Comment by kayceesrk** [comment]
There is now a written spec around what we expect from `stdlib` in Multicore OCaml: https://github.com/ocaml-multicore/ocaml-multicore/wiki/Safety-of-Stdlib-under-Multicore-OCaml.

**Comment by kayceesrk** [comment]
Fixed by #577 and #582.
