### ISSUE TITLE
[RFC] Domain.Sync vs Mutex/Condvar

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#387]
As we are reviewing #381, a question that keep cropping is what is the interaction between the synchronization constructs of DECs and domains. Domains are equipped with `Domain.Sync.{wait,notify}` and systhreads which are implemented on top of DECs synchronize using `Mutex` and `Condvar`. The natural question that comes up is whether `Mutex` and `Condvar` can be used to synchronize domains? This should be possible if one permits `Mutex` and `Condvar` to be used to synchronize DECs running on different domains. Two domains synchronizing using `Mutex` and `Condvaar` is the same as two DECs on two different domains synchronizing with each other. 

This begs the question. Is `Domain.Sync` necessary? Can we just do with `Mutex` and `Condvar`? Since backup threads were added in #356, `Mutex` and `Condvar` can safely be used to park the kernel threads servicing a domain since the backup thread will take care of participating in the GC. I've tried to write down the pros and cons of the two approaches below. 

## Critical section

Entering a `Domain.Sync.critical_section` does not involve atomic operations. In the fast path, when the calling domain does not need to `Domain.Sync.wait`, the operation does not involve any `pthread_*` operations. Whereas, if one were to use `Mutex` and `Condvar`, entering the critical section at the very minimum involves a `Mutex.lock` and `Mutex.unlock`, which inturn calls `pthread_mutex_lock` and `pthread_mutex_unlock`. On Linux, mutexes are implemented using Futexes, so the fast path will be reasonably fast. The downside is that, in order to service the GC interrupts, the backup thread must be woken up to handle the off chance that the lock is currently taken and the kernel thread needs to sleep. The question of whether `Domain.Sync.notify` needs to be synchronous (#386) can be preempted as we'd just have the semantics of underlying `Mutex` and `Condvar`. 

## Interactions between the synchronization constructs

In the current design, `Domain.Sync.wait` forces the domain to wait until notified, irrespective of whether there are other DECs available to run. This is bad for composability since one of the DECs `Domain.Sync.wait`ing can make other DECs starve. If one were to use the `Mutex` API, then trying to lock a mutex would release the `domain_lock`, which will permit other DECs and the backup thread to obtain the lock. This semantics is composable. 

## Evaluating the two solutions

It should be fairly easy to write a `Domainslib.Chan` implementation that uses `Mutex` and `Condvar` rather than `Domain.Sync`. Given that `Domainslib.Task` is built over `Domainslib.Chan` and all the parallel sandmark benchmarks are written using `Domainslib.Task`, we should be able to fairly quickly (est: a few days) get a performance comparison between the two implementations on the parallel benchmarks.

**Comment by kayceesrk** [comment]
There are draft PRs 

* #390 which adds mutexes and condition variables to domains
* https://github.com/ocaml-multicore/domainslib/pull/17 which implements channels based on mutexes and condition variables rather than `Domain.Sync`. 

The results on the turing (24 domains max):

![image](https://user-images.githubusercontent.com/410484/90971395-78ba8480-e52d-11ea-97d2-9e8b20f48108.png)

shows that the performance of mutex-condvar based implementation tapers out at higher core counts. My suspicion is that the difference is due to the thread switching overheads. With `Domain.Sync`, the main thread blocks on the interrupt condition variable, and is able to react quickly to the inter-domain interrupts for GC and domain wakeup. Whereas in the case of mutex-condvar solution, the waiting thread will wakeup the backup thread, which handles the GC interrupts. The main thread remains asleep until it is woken up by pthread signal from the signaling thread. _This suspicion needs to be confirmed_.

The performance on sherwood (128 domains max) is even more stark. Note: sherwood only uses taskset and does not use `chrt -r 1`, which I think is a more representative run since the scheduling is left to the OS:

![image](https://user-images.githubusercontent.com/410484/90973005-9393f580-e53b-11ea-9be9-598caf554235.png)

Note: @ctk21 the overall results appear less scalable than the one that you'd produced earlier. Am I looking at this right?

## Takeaway

PR390 shows that we can use mutex and condition variables to synchronize domains. For example, once the DEC PR (https://github.com/ocaml-multicore/ocaml-multicore/pull/381) lands, one could conceivably use the `Mutex` and `Condition` modules to synchronize two DECs running on two different domains But the cost of doing so will be higher than using `Domain.Sync`.

## Next steps

1. Identify the reason for the scalability issue with larger domain counts with mutex-condvar variant.
2. Implement any low-hanging performance improvements
3. Make a decision on whether to proceed with mutex-condvar or stick to `Domain.Sync`.

**Comment by ctk21** [comment]
There has been some progress on this:
 - Domainslib has been updated to use finer grained mutex/condvar: https://github.com/ocaml-multicore/domainslib/pull/19
 - We have tightened up the benchmarking methodology; particularly around taskset where we now enforce that the number of taskset cpus is the number of domains in all cases. This has more impact when the backup thread kicks in. 
 - We have overhauled the spinning in multicore to be more friendly when a system is loaded: https://github.com/ocaml-multicore/ocaml-multicore/pull/395

With these changes I was getting the following results on a machine that can use upto 128 domains:
![sherwood_big_no_turbo](https://user-images.githubusercontent.com/1682628/93600021-f485e080-f9b6-11ea-9c97-042da0b39f59.png)
In these results:
- `spin_chng` refers to #395
- `no_turbo` refers to switching off AMD CPB turbo so that results are a bit less affected by temperature
- `relaxed` refers to #397 
- `chrt` is the inclusion of `chrt -r 1` which is Linux `SCHED_RR` (round robin real-time process) instead of the default `SCHED_OTHER`

For larger domain counts you really need `chrt` to get the Mutex/Condvar to close the gap on `Domain.Sync`. For smaller domain counts Mutex/Condvar is respectable vs `Domain.Sync`.

**Comment by ctk21** [comment]
This design decision is now resolved: 
- `Mutex`, `Condition` & `Semaphore` are now first class Stdlib modules #548
- `Mutex` & `Condition` is now used for `Chan` in [domainslib 0.3.0](https://github.com/ocaml-multicore/domainslib/releases/tag/0.3.0) 
- `Domain.Sync` has been slimmed down to remove `wait`, `notify`, `critical_section` #561 

Closing the issue.
