### ISSUE TITLE
Abstract_tag blocks are incompatible with copy-based promotion

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#39]
The current strategy for sharing local heap objects is by making a copy of the object in the major heap. The runtime ensures that the writes performed to either copies of the promoted object is mirrored to the copy using a write fault mechanism. However, this design is incompatible with `Abstract_tag` blocks. 
C bindings use blocks with tag `Abstract_tag` as raw memory chunks, and read and write from them as raw C structures (which they often are). It'll be pretty hard to intercept such writes and mirror them in a copy or fault on them.

A workaround to this problem is to enforce the constraint that `Abstract_tag` blocks are only allocated in the major heap. In this case, `caml_alloc_small(size, Abstract_tag)` would be a runtime error. Instead, a new function `caml_alloc_abstract(size)` may be provided, which allocates directly in the major heap.

**Comment by bluddy** [comment]
What strategy is currently there for dealing with Abstract_tag blocks in the case of a minor garbage collection?

**Comment by kayceesrk** [comment]
`Abstract_tag` blocks are not traced by the GC, and hence shouldn't contain references to other OCaml objects. Otherwise, they are GCed as usual; minor collection promotes a live `Abstract_tag` block to the major heap. As long as the C binding registers a reference to an `Abstract_tag` block as a root, the object can be freely written to and read from, and it doesn't matter in which heap it resides.

**Comment by bluddy** [comment]
OK thanks. I think I've got it.

Here's a question: how worthwhile is it to have a sharing strategy that involves copying, when all that is required is a minor GC to move the entire value into the major heap?

Let me be a devil's advocate on my own question here: assuming we allow the user to make the minor heap large (in the order of MBs, as you can in Haskell), how do we deal efficiently with work-stealing between fibers, as that absolutely requires a minor GC?

**Comment by kayceesrk** [comment]
We've been experimenting with various promotion schemes, and one of those is to promote by performing minor GC: https://github.com/ocamllabs/ocaml-multicore/tree/promote-with-minor-gc. This scheme is conceptually simpler. Indeed, it does perform best on a subset of benchmarks. The main issue with this scheme is that we might promote objects too early. Generational hypothesis says that most objects die young. Objects that would have died young would now require a major GC to cleanup.

Another alternative is to *move* the requested object to the major heap and forward any local references to that object to its new location in the major heap: https://github.com/ocamllabs/ocaml-multicore/tree/move-based-promotion. This scheme doesn't promote objects early, which is great, but does require scanning local roots + certain parts of minor GC. Under workloads with frequent promotions, there is a lot of this forwarding work, which typically grows with the size of the minor heap. It is not clear if this is a win. It is possible to combine move-forward with move-minor-gc and dynamically make a choice based on the minor heap size.

The move-based schemes also require that the domain performing the promotion knows all the local roots, either for a minor GC or forwarding local roots. A subtle corner case can occur when two domains want to read from each other's minor heaps at the same time. Recall that reads from C bindings (i.e., `Field(x,i)`) are not safe-points in OCaml. But the cyclic dependence requires that both domains perform move-based promotion for progress. Hence, with move-based promotion accessing mutable fields from C bindings must be a safe-point. This is a breaking change for C bindings. Copy-based scheme doesn't have this problem since it copies and doesn't move.

At the end of the day, there is no clear winner here. What is needed is to (1) benchmark the different schemes on a large corpus of realistic multicore benchmarks to assess the performance and (2) assess the impact of breaking changes by porting a significantly large project using C bindings in a non-trivial fashion.

**Comment by bluddy** [comment]
Presumably, there would be some annotation so that shared data is immediately created on the major heap? This would then be the 'ideal' way to share data. If so, would it be safe to assume that the percentage of shared mutable data in the minor heap is low?

Also, I don't remember -- is copy/move promotion recursive, or do you only promote the currently requested block? 

It seems that you would want to use multiple strategies, and have heuristics for activating each one of them. For example, a single ref cell could be copied, a large array could be moved (though I'm not sure if a move is ever better significantly than a minor GC), and if a thread has many promotion requests pending, it should just do a minor GC. Ultimately you need some dynamic statistics here to help you make the decision, such as number of promotion requests pending and percentage of minor heap that needs to be promoted.

**Comment by kayceesrk** [comment]
> Presumably, there would be some annotation so that shared data is immediately created on the major heap? This would then be the 'ideal' way to share data. If so, would it be safe to assume that the percentage of shared mutable data in the minor heap is low?

See 4 in https://github.com/ocamllabs/ocaml-multicore/issues/42

> Also, I don't remember -- is copy/move promotion recursive, or do you only promote the currently requested block?

It is recursive.

> It seems that you would want to use multiple strategies, and have heuristics for activating each one of them.

In an ideal world, yes. But it complicates the already not so simple GC design/implementation, and will prohibit maintainability in the long run. Also, it is unclear whether heuristics would work in the general case. It is typical in these circumstances to benchmark the schemes on a representative class of programs and pick the one that works best among the alternatives.

**Comment by bluddy** [comment]
OK great. Thank you.

**Comment by stedolan** [comment]
This issue is irrelevant now that copy-based promotion's gone.
