### ISSUE TITLE
Atomic.create vs Atomic.make

### ISSUE THREAD

**Issue by dbuenzli** [ocamllabs/ocaml-multicore#393]
In a discussion that seems to have been lost by github. I suggested to @gasche to use `Atomic.create` instead of `Atomic.make` when he integrated the sequential implementation of `Atomic` in the stdlib https://github.com/ocaml/ocaml/pull/9570

The stdlib uses both `create` and `make` but the latter only mostly for arrays. I personally see no good reason to use `make` as `create` seems to be favored by other data structures of the stdlib (see [index of values](http://caml.inria.fr/pub/docs/manual-ocaml/libref/index_values.html) to convice yourself) and is reinforced by https://github.com/ocaml-multicore/ocaml-multicore/pull/390 

This should likely be resolved before 4.12 gets in the wild as it will provide the `Atomic` module in the stdlib.

**Comment by gasche** [comment]
I agree: `create` would be better and it is more consistent. (Sorry for not opening the issue myself, I wanted to revisit this eventually.) I would be happy to help by sending a PR if there is interest from ocaml-multicore developers. I expect that a fair amount of (experimental) Atomic-using code will have to be modified.

**Comment by dbuenzli** [comment]
> I expect that a fair amount of (experimental) Atomic-using code will have to be modified.

I think the easiest is to deprecate `make` in multicore and only provide `create` in `OCaml`.

**Comment by ctk21** [comment]
This looks reasonable to me. I've implemented the ocaml-multicore side here: #396 
We should probably do the ocaml/ocaml side before 4.12 hits the wild.

**Comment by gasche** [comment]
Great! Thanks for having done the ocaml-multicore side. For me the important question was whether there were opinions against the change among multicore people, or ideally a consensus in favor. If the feedback is positive (it looks positive, if maybe fairly quiet), we should go ahead and do the ocaml-side change early on.

**Comment by avsm** [comment]
Strong consensus from the multicore team in favour of switching to Atomic.create, and an even stronger consensus to not get out of sync with upstream OCaml :) Updating the existing code examples isn't a problem.

**Comment by gasche** [comment]
Thanks @avsm for the feedback. I just sent a PR to the Sequential-OCaml repository: https://github.com/ocaml/ocaml/pull/9921 .

**Comment by dbuenzli** [comment]
It seems upstream has its own logic between `make` and `create` and finds it sound and should be perpetuated. Nothing should be changed, sorry for the noise and churn.

**Comment by avsm** [comment]
That's no problem Daniel. Thanks for raising it; at least we've clarified that the convention exists now.
