### ISSUE TITLE
Domain-local allocation buffers - step 1: unified minor heap

### ISSUE THREAD

**Issue by sadiqj** [ocamllabs/ocaml-multicore#398]
Multicore currently has a separate minor heap per domain, a vestige of the concurrent minor collector. This issue is to get the details down for a unified minor heap, which is a prerequisite for domain-local allocation buffers.

The intention is that on startup the specified minor heap size will be pre-allocated for `Max_domains`.

When we create a new domain, if it doesn't already have an assigned range in the unified minor heap (which we can identify by looking at something in `Caml_state` left over from a previous domain), then we allocate it one.

To avoid having minor heap sitting around from Domains that are no longer required, we may want to reallocate all currently running Domains minor heaps at the end of a major cycle and then `MADV_DONTNEED` the rest of the reserved space.

@Engil @ctk21

**Comment by kayceesrk** [comment]
Closing this one as there is a negative performance impact due to this change. See PR https://github.com/ocaml-multicore/ocaml-multicore/pull/508 and the summary of the work done https://github.com/ocaml-multicore/ocaml-multicore/wiki/Domain-Local-Allocation-Buffers-Addendum.
