### ISSUE TITLE
Backport Garbage Collector Colours change

### ISSUE THREAD

**Issue by sadiqj** [ocamllabs/ocaml-multicore#399]
Now that the GC colours change (https://github.com/ocaml/ocaml/pull/9756) has been merged to trunk, we should port the changes over to Multicore.

I think these are:
* the optimisations in `mark_stack_push`
* the representation of `mark_entry` (no longer storing end)
* marking behaviour

This is also a good opportunity to simplify by removing the existing `addrmap` implementation and something similar to https://github.com/ocaml/ocaml/pull/9756. We don't need skip lists in Multicore as the Pools in the allocator are all of fixed size.

The trunk PR also includes shrinking the mark_stack which may be something we want to consider.

@Sudha247 @kayceesrk

**Comment by Sudha247** [comment]
Done in #427 and #435.
