### ISSUE TITLE
beat.ml test failure on MacOS+clang

### ISSUE THREAD

**Issue by abbysmal** [ocamllabs/ocaml-multicore#408]
I open this issue to keep track of the `beat.ml` testcase in `lib-threads`.
This test currently fails on MacOS + clang with the following error:
`FAILED (n1 = 7, n2 = 5)`
(which is an off-by-one error in the expect computed counters.)

**Comment by kit-ty-kate** [comment]
Sounds like it's an issue encountered with upstream OCaml 4.10 (see mention above)
