### ISSUE TITLE
flambda removing Domain.Sync.poll

### ISSUE THREAD

**Issue by ctk21** [ocamllabs/ocaml-multicore#412]
flambda builds are not passing compiler testsuite.

If you build with flambda (using `--enable-flambda` with `./configure`) and then run `tests/parallel`, the suite will hang on the `poll` test.

Slightly embarrassingly it looks like flambda has removed the poll in the function `loop`:
```ocaml
let rec loop () =
  Domain.Sync.poll ();
  loop ()
```
gets compiled to:
```assembly
00000000000a50b0 <camlPoll__loop_5>:
   a50b0:       b8 01 00 00 00          mov    $0x1,%eax
   a50b5:       eb f9                   jmp    a50b0 <camlPoll__loop_5>
```

With flambda off, we get the expected:
```assembly
0000000000061a80 <camlPoll__loop_82>:
   61a80:       b8 01 00 00 00          mov    $0x1,%eax
   61a85:       4d 3b 3e                cmp    (%r14),%r15
   61a88:       72 07                   jb     61a91 <camlPoll__loop_82+0x11>
   61a8a:       b8 01 00 00 00          mov    $0x1,%eax
   61a8f:       eb ef                   jmp    61a80 <camlPoll__loop_82>
   61a91:       e8 32 b0 06 00          callq  ccac8 <caml_call_poll>
   61a96:       eb f2                   jmp    61a8a <camlPoll__loop_82+0xa>
```

**Comment by lthls** [comment]
In `middle_end/semantics_of_primitives.ml`, the `Ppoll` primitive is marked as having only generative effects and no coeffects. Flambda is correct in eliminating code that has only generative effects.
I think the correct fix is to mark `Ppoll` as having arbitrary effects, but hopefully someone more familiar with multicore can confirm that.

**Comment by kayceesrk** [comment]
> I think the correct fix is to mark Ppoll as having arbitrary effects, but hopefully someone more familiar with multicore can confirm that.

That sounds like the correct fix.
