### ISSUE TITLE
Bad 'unused type effect' warning

### ISSUE THREAD

**Issue by ctk21** [ocamllabs/ocaml-multicore#417]
There is a spurious warning when using the keyword `effect` with `match`. 

Here is an example that triggers the problem:
```ocaml
effect E : unit

let h g =
  match perform E; g () with
  | _ -> 1
  | effect E _ -> 2
```
This gives the following warning when compiled with `ocamlopt -w +a effects_bad_warn.ml`:
```
File "effects_bad_warn.ml", lines 4-6, characters 2-19:
4 | ..match perform E; g () with
5 |   | _ -> 1
6 |   | effect E _ -> 2
Warning 34: unused type effect.
```
Can be annoying with `dune` where the default behaviour is to error on warnings.

**Comment by lpw25** [comment]
Someone should change [this line](https://github.com/ocaml-multicore/ocaml-multicore/blob/parallel_minor_gc/typing/typecore.ml#L4582) to use `add_type` with `~check:false` instead of `enter_type`.
