### ISSUE TITLE
Benchmark various promotion schemes

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#42]
Benchmark various promotion schemes
1. **copy-based promotion:** Promote by making a copy of the promoted object in the major heap. Requires write faults to mirror writes to both copies: https://github.com/ocamllabs/ocaml-multicore/tree/master
2. **move-forward promotion:** Promote by moving the object, and forward any local references to the promoted object. Mutable reads must be safe-points: https://github.com/ocamllabs/ocaml-multicore/tree/move-based-promotion
3. **move-gc promotion:** Promote by performing a minor GC. Mutable reads must be safe-points: https://github.com/ocamllabs/ocaml-multicore/tree/promote-with-minor-gc
4. **mutable-in-major promotion:** Allocate all mutable objects and stacks in the major heap. Promote by copy, but does not require write faults since there are no mutable objects in the minor heap.
5. **synchronized minor GCs:** Heap invariant that prohibits minor to minor pointers is not necessary since the minor GCs are synchronized. This is essentially a stop-the-world parallel minor GC.
6. ~~**synchronized minor GCs on read-fault cycles:** A variant of move-based promotion that synchronizes the minor GCs of domains that become part of read-fault cycles. The main advantage is that mutable reads need not be safe-points. Very tricky.~~  **synchronized minor GCs on read-faults:** A variant of 5. Minor GCs become coupled on read-faults. There is no promotion (and the associated problems). Minor GCs are independent if there are no read-faults.

**Comment by lpw25** [comment]
> synchronized minor GCs on read-fault cycles

When I suggested synchronized minor GCs on read-faults, I was actually referring to a scheme which allows minor heaps to be collected asynchronously until there is a read fault -- at which point the reading domain would ask for permission to read directly from the owning domain's minor heap. Then the minor collections of those domains would be marked as needing to be done synchronously.

The hope is that work stealing would be infrequent enough that the majority of collections would not need to synchronise -- or at least would only need to synchronise with a low number of other domains.

**Comment by lpw25** [comment]
> mutable-in-major promotion

I suspect that we will not be able to get away with something as simple as merely allocating mutable objects on the major heap. I suspect it will do too much damage to the generational hypothesis. However, something which allocates mutable objects into the same space as the major GC but still tracks the young generation separately from the old generation seems quite promising.

**Comment by stedolan** [comment]
I think 6 is almost unimplementably complicated, so I don't think we should bother with it. The main problem is that it's untestable: it contains tricky algorithms that only run in very rare circumstances, so it could run some workload for years without issue but fail on something else.

The point of 5 is that the read fault can be avoided. Before we try implementing it, we can simply disable the read fault in one of the other schemes and run some benchmarks that don't require faulting. If the benefit of avoiding the read fault is small, there's no point implementing 5.

**Comment by lpw25** [comment]
@stedolan What about the version of 6 that I mentioned above?

**Comment by bluddy** [comment]
An orthogonal point: have you thought about allocating in different arenas for different cores in the major GC as JEMalloc does? That would reduce contention between cores.

**Comment by stedolan** [comment]
> I suspect that we will not be able to get away with something as simple as merely allocating mutable objects on the major heap. I suspect it will do too much damage to the generational hypothesis. However, something which allocates mutable objects into the same space as the major GC but still tracks the young generation separately from the old generation seems quite promising.

Probably right. Non-moving but still generational GC for mutable blocks using the major heap's allocator does sound quite promising.

I think either version of 6 is too hard to get right (or at least blows too much of the complexity budget on a minor part of the system). The biggest issue is that there's a complicated mechanism that only kicks in under rare circumstances, which makes testing difficult.

**Comment by stedolan** [comment]
> An orthogonal point: have you thought about allocating in different arenas for different cores in the major GC as JEMalloc does? That would reduce contention between cores.

The shared heap allocator (`shared_heap.c`) already does this. It doesn't affect how we do promotions.

**Comment by lpw25** [comment]
@stedolan I don't think I explained my proposal properly. I mean synchronising minor collections *whenever there is a read fault*. So there would be no promotion, but there would still be a read barrier to allow unrelated collections to proceed without synchronising.

**Comment by bluddy** [comment]
Quick question gentlemen: work stealing is really going to tax the system in terms of premature minor GC, right?

**Comment by kayceesrk** [comment]
@lpw25 Updated the proposal 6. I believe this should be relatively easy to do on top of 5. This is worth considering.

**Comment by stedolan** [comment]
@lpw25: I did misunderstand: when you wrote "read fault" I was instead thinking of "race between two read faults". I think what you're actually proposing sounds more sensible, and quite testable.

@bluddy: A good work-stealing system, oddly, does very little work-stealing. The idea is to keep as much scheduling as possible local to each domain, so that the actual stealing of work is a very, very rare case. Almost any optimisation which speeds up the non-stealing case, even at the expense of slowing down actual cross-domain stealing, is good for performance. So, the performance of an actual steal event isn't hugely important to the performance of work-stealing.

**Comment by kayceesrk** [comment]
The current GC has settled into using move-based promotion that combines 2 and 3. Copy-based promotion is broken for `Abstract_tag` objects. Scheme 4 (mutable in major heap) is bad for generational behaviour. Scheme 5 (synchronized minor GCs) requires a good chunk of engineering and optimisations before it could be usefully benchmarked against the current scheme. Moreover, it imposes a latency hit for minor GCs. 

Closing this issue for now as it is unlikely to be addressed in the short-term. To be reopened if there is strong support for synchronised minor GCs.
