### ISSUE TITLE
Issues with `Mutex.try_lock`

### ISSUE THREAD

**Issue by toots** [ocamllabs/ocaml-multicore#425]
Hi!

I've followed the steps outlined by Anil [here](https://discuss.ocaml.org/t/multicore-ocaml-september-2020/6565) to install the multicore compiler and am running into an issue with this code:
```ocaml
let () =
  let m = Mutex.create () in
  Mutex.lock m;
  assert(not (Mutex.try_lock m))
```
After compiling and running it:
```shell
% ./test.exe
Fatal error: exception File "./test.ml", line 4, characters 2-8: Assertion failed
Raised at file "string.ml", line 115, characters 19-34
Called from file "string.ml", line 179, characters 15-34
zsh: exit 2     ./test.exe
```

Details:
* OCaml: `4.10.0 [ocaml-multicore-ocaml-multicore-no-effect-syntax]`

**Comment by abbysmal** [comment]
Thank you very much for your report!

As a side note, I am unsure what was your usecase with it, but Mutex (as the module stands right now in multicore, when linked with systhreads), are expected to be used for cross-systhreads interactions.
If your intended usecase is cross-domains interactions, the following document will provide you with the current abstractions:
https://github.com/ocaml-multicore/parallel-programming-in-multicore-ocaml
For now the Mutex module is a part of systhreads, and while it *may* work accross domains (there is a few testcases in the testsuite), this is maybe not the better path. :)
We do have a work in progress toward enabling Mutex and Condition for cross-domains interactions, but it is not merged yet:
https://github.com/ocaml-multicore/ocaml-multicore/pull/390
