### ISSUE TITLE
Refactor `Field` for move-based promotion

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#43]
Move-based promotion schemes require that access to accessing fields of mutable objects be safe-points. The idea is to remove `Field` macro from the C interface and instead provide `Mutable_field` and `Immutable_field` macros for accessing mutable and immutable object fields. `Mutable_field` must be a safe-point.

**Comment by stedolan** [comment]
See https://github.com/ocamllabs/ocaml-multicore/wiki/C-API-changes
