### ISSUE TITLE
Refactor `DELEGATE` to `REPERFORM`

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#44]
and refactor `delegate` to `reperform`, which is more consistent with `reraise`.

**Comment by clappski** [comment]
Is this ticket still open? It was raised a while ago, and having a quick grep through the code shows a few places using `delegate`.

**Comment by kayceesrk** [comment]
Yep. The issue is still open. Would you like to contribute a PR?

**Comment by clappski** [comment]
Definitely, I'll put one together this evening.

**Comment by clappski** [comment]
Please see the [pull request](https://github.com/ocamllabs/ocaml-multicore/pull/48). Let me know if the scope of the changes are too broad or too narrow.
