### ISSUE TITLE
reintroduce caml_stat_ accessors in the C API

### ISSUE THREAD

**Issue by abbysmal** [ocamllabs/ocaml-multicore#448]
We were checking with @kit-ty-kate some recent build failures on the Opam CI for Multicore
core kernel currently fails on such errors:
```
- gc_stubs.c: In function 'minor_words':
- gc_stubs.c:7:20: error: 'caml_stat_minor_words' undeclared (first use in this function)
-     7 |   return (intnat) (caml_stat_minor_words +
-       |                    ^~~~~~~~~~~~~~~~~~~~~
- gc_stubs.c:7:20: note: each undeclared identifier is reported only once for each function it appears in
- gc_stubs.c:8:23: error: 'caml_young_end' undeclared (first use in this function)
-     8 |             (double) (caml_young_end - caml_young_ptr));
-       |                       ^~~~~~~~~~~~~~
- gc_stubs.c:8:40: error: 'caml_young_ptr' undeclared (first use in this function)
-     8 |             (double) (caml_young_end - caml_young_ptr));
-       |                                        ^~~~~~~~~~~~~~
- gc_stubs.c: In function 'promoted_words':
- gc_stubs.c:13:20: error: 'caml_stat_promoted_words' undeclared (first use in this function)
-    13 |   return ((intnat) caml_stat_promoted_words);
-       |                    ^~~~~~~~~~~~~~~~~~~~~~~~
- gc_stubs.c: In function 'major_words':
- gc_stubs.c:23:20: error: 'caml_stat_major_words' undeclared (first use in this function)
-    23 |   return (intnat) (caml_stat_major_words + (double) caml_allocated_words);
-       |                    ^~~~~~~~~~~~~~~~~~~~~
- gc_stubs.c:23:53: error: 'caml_allocated_words' undeclared (first use in this function); did you mean 'caml_orphan_allocated_words'?
-    23 |   return (intnat) (caml_stat_major_words + (double) caml_allocated_words);
-       |                                                     ^~~~~~~~~~~~~~~~~~~~
-       |                                                     caml_orphan_allocated_words
- In file included from /home/opam/.opam/4.10.0+multicore+no-effect-syntax/lib/ocaml/caml/gc.h:20,
-                  from /home/opam/.opam/4.10.0+multicore+no-effect-syntax/lib/ocaml/caml/memory.h:26,
-                  from gc_stubs.c:2:
- gc_stubs.c: In function 'core_kernel_gc_minor_collections':
- gc_stubs.c:38:19: error: 'caml_stat_minor_collections' undeclared (first use in this function); did you mean 'caml_minor_collection'?
-    38 |   return Val_long(caml_stat_minor_collections);
-       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
- /home/opam/.opam/4.10.0+multicore+no-effect-syntax/lib/ocaml/caml/mlvalues.h:82:47: note: in definition of macro 'Val_long'
-    82 | #define Val_long(x)     ((intnat) (((uintnat)(x) << 1)) + 1)
```
It seems we do not expose such fields in Multicore:
https://github.com/ocaml/ocaml/blob/trunk/runtime/caml/gc_ctrl.h
I tried to work out a solution for a while, but I think there's a few different approaches that would need some discussions.

(note, reading on #433 and #446 could be useful regarding the current and potential gc stats infrastructure.).

The idea is that on stock OCaml, these stats are straightforward to provide to such accessors, in Multicore the semantics are a bit blurry, as well as the potential implementation.

In Multicore, we have the `gc_sampled_stats[Max_domains]` array that gather periodically (major cycle in current HEAD for Multicore, and tentatively minor cycle in #446) stats, that are then aggregated when calling the high levels API to fetch these statistics.
Now, accessing such fields in Multicore begs the following questions: are these fields a "per domain" information (in which case, they would echo `gc_sampled_stats[self]`, or are they aggregated stats as well?

Because every other API accessing these stats in Multicore provide aggregated information. (`OCAMLRUNPARAM=v-0x400` for instance provides the overall program's statistics).
Introducing a subtly different behavior in the same API class would induce confusion, in my opinion.
At the same time, it is unclear to me how to properly implement these: on a per domain basis, we would just fetch the right fields in the right index for `gc_sampled_stats`.

In the aggregated route, we would need to aggregate these data in another way. (which sounds, either performance wise, or correctness wise, maybe sketchy.)

**Comment by kayceesrk** [comment]
One backwards compatible solution might be that these remain per domain, and we introduce new API for getting the global stats. For example, there might be a reasonable program which expects to see the `caml_stat_minor_words` to change after an allocation. This would not be the case if we returned from the sampled stat. I would think that both of these, i.e, reading the sampled stat and reading the domain local one, are useful.

**Comment by abbysmal** [comment]
Note:
#590 was merged (and went with the approach of using live stats rather than sampled ones for now.).
What was omitted from this PR was the inclusion of a few counters (I forgot to double check with trunk.)

For instance the `caml_stat_young_start` is missing, see:
http://check.ocamllabs.io:8082/log/1624377054-df20c61009ce6b16d04ffcfe43ef26c629c2599c/4.12+domains+gc_stubs/bad/grenier.0.12

**Comment by ctk21** [comment]
closing
If new issues arise, then they can be dealt with when reported
