### ISSUE TITLE
Implement default handlers

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#45]
Default handlers have been implemented for bytecode in ocaml-effects: https://github.com/lpw25/ocaml-effects/tree/default-handlers

**Comment by kayceesrk** [comment]
@dhil you had mentioned that you would like to implement default handlers for multicore. The relevant commits from `ecaml-multicore` are https://github.com/lpw25/ocaml/commit/f098d35e3b7e2b8ed58549236745dfe23ac19a99 and https://github.com/lpw25/ocaml/commit/bd0e22d9517315e4a384dcba49a0bc48818cc820.

**Comment by dhil** [comment]
Yes. I will look into this during the weekend. 

I do not have sufficient privileges on Github to assign the task to myself.

**Comment by dhil** [comment]
I suppose I will have port the syntax and typing changes as well, starting from [lpw25/ocaml@`2f33aad`](https://github.com/lpw25/ocaml/commit/2f33aad1d44b8906646536bdef98938a762fab19).

**Comment by kayceesrk** [comment]
> I do not have sufficient privileges on Github to assign the task to myself.

Done.

**Comment by dhil** [comment]
Yesterday, when we discussed the semantics of default handlers it became clear that we need to take care. After our discussion I went and had a look at my notes. From my notes I have compiled a list of questions.

## Synopsis
A default handler provides a *default* implementation of an effectful operation. An invocation of an operation will be handled by its default if no other handler for that operation is in scope. If a handler for the operation is in scope of the invocation then it overloads the default implementation.

## Proposed syntax 
The proposed syntax is closely aligned with Leo's implementation in ecaml.
At the top level: A default handler is declared along with an operation declaration using the `with function` syntax, e.g. 
```ocaml
effect Foo : int -> int with function
                             | Foo 42 -> 42
                             | Foo i -> 42 - i
```
This declares an operation `Foo` with a default handler (or default implementation) which interprets `perform (Foo i)` as either the constant `42` or the difference `42 - i` depending on the value of `i`.

For modules we have two levels of operation declarations: signature and structure declarations. For the former the proposed syntax is
```ocaml
module type M = sig
     effect Foo : int -> int with function
end
```
This module expose a single operation `Foo` which has a default handler. By contract, any implementation of `M` must provide a default handler for the operation `Foo`.

For structures we adopt the top level syntax, i.e.
```ocaml
module N = struct
   effect Foo : int -> int with function
                                 | Foo 42 -> 42
                                 | Foo i    -> 42 - i
end
``` 

## Semantics 
Now for the more interesting part. The semantics of default handlers.

**Question 1:** What are the semantics of pure default handlers? Do they get pushed onto the stack? Do they get inlined? (I imagine the latter requires effect tracking)

**Question 2:** What are the semantics of impure default handlers? As an example consider the following program.
```ocaml
effect Foo : int with function Foo -> 42
effect Bar  : int -> int with function Bar i -> i + perform Foo
```
The default implementation of `Foo` is pure, while the implementation of `Bar` is impure. It seems reasonable that `perform (Bar i)` should evaluate to `i + 42`. But what about the following program.
```ocaml
effect Foo : int
effect Bar  : int -> int with function Bar i -> i + perform Foo
```
Now `Foo` does not have a default implementation. But the default implementation of `Bar` invokes `Foo`. The question is whether declaration of `Bar` should be rejected as illegal or accepted with an undefined semantics?

**Question 3:** How about self invocation? Consider the following program.
```ocaml
effect Foo : int with function Foo -> perform Foo
```
Does this cause an infinite loop? Is the right hand side `Foo` even in scope of the default handler? 

**Question 4:** It would seem that default handlers cannot be mutually recursive. But, enter recursive modules... So what are the semantics of mutually recursive default handlers? 
Consider the following program.
```ocaml
module rec Even : sig
   effect IsEven : int -> bool with function
end = struct
   effect IsEven : int -> bool with function
                                    | IsEven 0 -> true
                                    | IsEven n -> perform (Odd.IsOdd (n-1))

end
and Odd : sig
   effect IsOdd : int -> bool with function
end = struct
   effect IsOdd : int -> bool with function
                                   | IsOdd 0 -> false
                                   | IsOdd n -> perform (Even.IsEven (n-1))
end
```

**Question 5:** Can an implementation provide a default handler if the handler is not mentioned by the interface? Concretely, consider the following program.
```ocaml
module type M = sig 
  effect Foo : int -> int
end

module N : M = struct
   effect Foo : int -> int with function | Foo i -> i
end
```

**Question 6:** If an operation is rebound does it inherit the potential default handler? Consider the following program.
```ocaml
module M = struct
   effect Foo : unit with function Foo -> unit
end

effect Foo = M.Foo
```  
Does this mean the toplevel `Foo` has inherited the default handler of `M.Foo`? Furthermore, does rebinding permit redefinition of any default handlers? For example
```ocaml
module M = struct
   effect Foo : unit with function Foo -> unit
end

effect Foo = M.Foo with function Foo -> assert false
```

**Comment by lpw25** [comment]
My answers to these questions.

1. They can in theory be executed on the top of the stack, but I doubt that optimisation will be that useful so I wouldn't bother with it.

2. The first example should return `i + 42` the second should raise `Unhandled`. Easiest way to think of it is to treat.

```
effect Foo : int
```
as equivalent to:
```
effect Foo : int with function Foo -> raise Unhandled
```

(Note this is different from the typed version of effects -- there we just ban the second example)

3 & 4. I think self-invocation and mutually recursive invocation is fine. It seems like it could arise quite naturally and doesn't seem too problematic semantically. Where this a total language we would have to be more careful -- but we're not so the more recursion the merrier.

5. I wouldn't bother mentioning default handlers in interfaces for the untyped version of effects. You don't use the information in any way so why bother to track it.

6. Yes it inherits the default handler. No you can't change them.

**Comment by dhil** [comment]
Thanks @lpw25. Regarding your comment on item 2
> The first example should return i + 42 the second should raise Unhandled. Easiest way to think of it is to treat.
> ```effect Foo : int```
>
> as equivalent to:
>
> ```effect Foo : int with function Foo -> raise Unhandled```
This essentially means in the untyped version every operation has a default handler, namely, one which raises`Unhandled`.

**Comment by lpw25** [comment]
Yeah. I think this mental model is simpler to think about.

**Comment by stedolan** [comment]
I have another question, which I don't think is covered by 1-6.

**Question 7**: In which effect-handling context do default handlers run? For instance, what does the following program print?

```ocaml
effect Foo : unit with function Foo -> print_string "outside"
effect Bar : unit with function Bar -> perform Foo
let _ =
  match (perform Bar) with
  | () -> ()
  | effect Foo -> print_string "inside"
```

The `perform Bar` is unhandled, so the default handler runs and performs `Foo`. Is the expression `perform Foo` evaluated at the site of `perform Bar` (in which case `"inside"` will be printed), or evaluated in a virtual match statement enclosing the entire program (in which case `"outside"` will be printed)?

**Comment by lpw25** [comment]
7. It is evaluated at the top-level, so `outside` will be printed.

**Comment by dhil** [comment]
I am trying to implement the following typing rule,
```
       [ G, E : T1 -> T2, x_i : T1 |- N_i : T2 ]_i 
----------------------------------------------------------
 G |- effect E : T1 -> T2 with function [ E x_i -> N_i ]_i
```
where `G` is an environment, `E` is an operation name, and the notation `[ ... ]_i` denotes a nonempty collection indexed by `i`. I think this rule provides a good first approximation. The main idea is that the clause bodies `N_i` must have the same type as the return type of `E` since the continuation is wrapped implicitly around each clause body. 

I suppose I have to augment [`transl_effect`](https://github.com/ocamllabs/ocaml-multicore/blob/master/typing/typedecl.ml#L1340) in [typedecl.ml](https://github.com/ocamllabs/ocaml-multicore/blob/master/typing/typedecl.ml), furthermore I am hoping to reuse (at least parts of) [`type_effect_cases`](https://github.com/ocamllabs/ocaml-multicore/blob/master/typing/typecore.ml#L3615) from [typecore.ml](https://github.com/ocamllabs/ocaml-multicore/blob/master/typing/typecore.ml) for typing the effect cases.

After trying to implement the rule I get the following error
```ocaml
# effect E : int -> unit with function E i -> ();;
Error: Effect patterns must be at the top level of a match case.
```
I am not sure why this error is triggered. Part of the problem is that I do not fully understand how the type checker works. There seems to be a lot of state floating around. I suppose the above error is happening because I do not understand the `level` system in the type checker (e.g. [`get_current_level ()`](https://github.com/ocamllabs/ocaml-multicore/blob/master/typing/typecore.ml#L3620))

Maybe you, @lpw25, could provide me with some pointers on how to go about and implement the above rule in the type checker?

**Comment by stedolan** [comment]
> I suppose the above error is happening because I do not understand the level system in the type checker (e.g. get_current_level ())

[Oleg's article](http://okmij.org/ftp/ML/generalization.html) explains levels.

**Comment by lpw25** [comment]
Firstly, have you looked at [this implementation](https://github.com/lpw25/ocaml-effects/commit/8a0349246f072e8c57115aeba27f9b90f59600d0)?

I don't think that error is related to levels though. It looks to me like a syntactic restriction from some of my code in typecore.ml.

**Comment by lpw25** [comment]
Yeah, it comes from [here](https://github.com/ocamllabs/ocaml-multicore/blob/master/typing/typecore.ml#L1229) in `type_pat`, which expects the effect cases to have already been removed in places like [here](https://github.com/ocamllabs/ocaml-multicore/blob/master/typing/typecore.ml#L1986).

**Comment by dhil** [comment]
Thanks @stedolan!

Thanks @lpw25, I had been looking at much more recent code. I will look at the implementation which you linked instead.

**Comment by kayceesrk** [comment]
Closing in favour of implementation from @lpw25's typed effects work.
