### ISSUE TITLE
Note/TODO for OCaml 5.0: Get rid of compatibility.h

### ISSUE THREAD

**Issue by kit-ty-kate** [ocamllabs/ocaml-multicore#451]
In https://github.com/garrigue/lablgl/pull/2, I fixed lablgl for it to work with ocaml-multicore.
Currently ocaml-multicore removed `modify` and `initialize` from `compatibility.h` which incidently broke `lablgl`, but it's not a big deal, I don't think they should be brought back at all.

Back during the OCaml 4.10 release period, there was already some talks about removing `compatibility.h` and I think it would be good to do that for OCaml 5.0, that'll be a breaking change in the good direction.

So I'm creating this issue as a TODO for later during the upstream merge period for OCaml 5.0, or as a place to discuss if people want to remove it earlier, or not at all. Feel free to close it if it does not serve any purpose though.

**Comment by avsm** [comment]
This is a very useful reminder, thanks!

**Comment by dra27** [comment]
There are a whole series of housekeeping tasks for OCaml 5.00 which I (at least, I think it's going to end up being me!) need to discuss. This is a very useful reminder to ensure "resetting" compatibility.h is on the list, too!

**Comment by kit-ty-kate** [comment]
Fixed by https://github.com/ocaml/ocaml/pull/10863
