### ISSUE TITLE
no-effect-syntax still contains the effect syntax on the Typedtree

### ISSUE THREAD

**Issue by EduardoRFS** [ocamllabs/ocaml-multicore#457]
By trying to use merlin with the no-effect-syntax I noticed that the current implementation still has the effect system on the typed AST and was pointed out by @kayceesrk that it should be removed

Ideally from a user-space perspective the `.cmi` file would have the same runtime representation as the one upstream, as it uses the same cmi magic number

**Comment by Sudha247** [comment]
Fixed by #458.
