### ISSUE TITLE
Error in package ocaml-migrate-parsetree

### ISSUE THREAD

**Issue by kyp0717** [ocamllabs/ocaml-multicore#465]
Please see error below ..
```
[ERROR] The compilation of ocaml-migrate-parsetree failed at "/home/opam/.opam/4.10.0+multicore/bin/dune build -p ocaml-migrate-parsetree -j 47".

#=== ERROR while compiling ocaml-migrate-parsetree.1.8.0 ======================#
# context              2.0.7 | linux/x86_64 | ocaml-variants.4.10.0+multicore | file:///home/opam/opam-repository
# path                 ~/.opam/4.10.0+multicore/.opam-switch/build/ocaml-migrate-parsetree.1.8.0
# command              ~/.opam/4.10.0+multicore/bin/dune build -p ocaml-migrate-parsetree -j 47
# exit-code            1
# env-file             ~/.opam/log/ocaml-migrate-parsetree-8-d429e8.env
# output-file          ~/.opam/log/ocaml-migrate-parsetree-8-d429e8.out
### output ###
#       ocamlc src/.migrate_parsetree.objs/byte/migrate_parsetree__Ast_410.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.10.0+multicore/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.migrate_parsetree.objs/byte -I /home/opam/.opam/4.10.0+multicore/lib/ocaml/compiler-libs -I /home/opam/.opam/4.10.0+multicore/lib/ppx_derivers -I /home/opam/.opam/4.10.0+multicore/lib/result -no-alias-deps -open Migrate_parsetree__ -o src/.migrate_parsetree.objs/byte/migrate_parsetree__Ast_410.cmo -c -impl src/ast_410.pp.ml)
# File "src/ast_410.ml", lines 248-303, characters 2-44:
# Error: This variant or record definition does not match that of type
#          Parsetree.pattern_desc
#        Constructors number 17 have different names, Ppat_effect and Ppat_extension.
```
The same issue occurs with ocaml-migrate-parsetree.2.1.0 .

**Comment by Sudha247** [comment]
Thanks for the report @kyp0717! `ocaml-migrate-parsetree` doesn't work with `4.10.0+multicore` yet, due to the changes in multicore's AST to support effect handlers.

In order to use `ocaml-migrate-parsetree` (and ppx) with multicore, it is recommened to do it in the `4.10.0+multicore+no-effect-syntax` compiler variant, which does not have the effect syntax extensions. Installation instructions for the same can be found [here](https://github.com/ocaml-multicore/multicore-opam#install-multicore-ocaml).

**Comment by Sudha247** [comment]
We also have a version of `ocaml-migrate-parsetree` with addition of effect syntax now, that works with `4.12+domains+effects` & `4.10.0+multicore` here - https://github.com/ocaml-multicore/multicore-opam/pull/46. To make this clear, `ocaml-migrate-parsetree` works out of the box with `4.12+domains` & `4.10.0+multicore+no-effect-syntax`, to install it in compiler variants with effect sytax you can use the patch I've mentioned above. 

Please let us know if there are any other issues with `ocaml-migrate-parsetree`, closing this one.
