### ISSUE TITLE
Building on musl requires dynamically linked execinfo

### ISSUE THREAD

**Issue by hyphenrf** [ocamllabs/ocaml-multicore#473]
multicore fails to build without libexecinfo. The dependency seems to be the `backtrace_symbols` function in [`misc.c`](../blob/e6017/runtime/misc.c#L59), usually expected to exist in glibc itself without external linkage. I'm not sure if `#include <execinfo.h>` was introduced in multicore or if it comes from upstream, but it dates back to 2016. Either way, this issue is unique to multicore now.

Attempting to pass `-lexecinfo` to `configure` via the `CFLAGS`, `LIBS`, `DLLIBS` seems to have no effect. Reading through the configure script I saw an undocumented variable which may be used to inject the flag: `cclibs`.

```sh
export cclibs=-lexecinfo
./configure ...
make
```

Doing it like this seems to work.
Tested on Alpine 3.12.1

PS: what's the best way to streamline this into the build process? I'm hoping to write an OPAM file for a musl compiler variant. And `cclibs` feels like a hackish approach.

**Comment by avsm** [comment]
Let us know how your musl experiments go @hyphenrf -- both the multicore and the no-effects-syntax branches have this fix now.  There are base images for multicore building now on Docker Hub as well in ocaml/opam, in case thats of any use.

**Comment by hyphenrf** [comment]
Thank you -- both branches now work without hiccups!
I didn't even realize we could just specify the missing dep in `configure.ac`. That's definitely better than doing it manually.
