### ISSUE TITLE
Segfault while running the layers benchmark.

### ISSUE THREAD

**Issue by shubhamkumar13** [ocamllabs/ocaml-multicore#485]
**Bug Descripiton :**  This segfault occurs when I try to run the [layers benchmark](https://github.com/shubhamkumar13/sandmark/blob/layers-bench/benchmarks/irmin/layers.ml) with larger values like `-n 1000` or the default value which is used when no argument is passed (4096) in this case

**Reproduction Steps :**

Step 1 - Clone the [repo](https://github.com/shubhamkumar13/sandmark/tree/layers-bench) and checkout the `layers-bench` branch. 
```
git clone https://github.com/shubhamkumar13/sandmark.git &&
cd sandmark &&
git checkout layers-bench
```

Step 2 - This is an optional step to add the multicore switch (goto Step 3 if you already have a multicore switch but using a fresh switch is recommended). To add the mulitcore switch you can follow the the [README](https://github.com/ocaml-multicore/multicore-opam/blob/master/README.md) file on the multicore opam.

Step 3 - Before starting with adding all the dependencies one needs to clone `ocaml-migrate-parsetree` (from [here](https://github.com/Sudha247/ocaml-migrate-parsetree.git)) and `ppxlib` (from [here](https://github.com/Sudha247/ppxlib.git)) because the ones on the opam repository do not build with multicore. 

Then checkout the `mulitcore` branch for both repos. 

After checking out that particular branch pin the packages using the following commands - 
- `opam pin ocaml-migrate-parsetree.dev .` when you are inside the `ocaml-migrate-parsetree` directory 
- `opam pin ppxlib.dev .`  when you are in the `ppxlib` directory. 

After pinning the 2 packages we can move forward with installing the depedencies for the benchmark.

Step 4 - Download the opam export file from [here](https://gist.githubusercontent.com/shubhamkumar13/515a221e2f66d729b2dacb0f55095b5a/raw/99d25456ad12c22e2d5eb02a91cc3e922774b6ca/layers.export) and import it to the current multicore switch.
```
wget https://gist.githubusercontent.com/shubhamkumar13/515a221e2f66d729b2dacb0f55095b5a/raw/99d25456ad12c22e2d5eb02a91cc3e922774b6ca/layers.export
opam sw import layers.export
```

Step 5 - Finally, goto the irmin benchmark directory `cd ./benchmarks/irmin/`

Step 6 - Try to build the benchmark to manually - `dune build layers.exe`

If you get an error similar to this 
```
Entering directory '/home/sk/shubham_sandmark/sandmark'
File "dune", line 1, characters 0-23:
1 | (include runs_dune.inc)
    ^^^^^^^^^^^^^^^^^^^^^^^
Error: File runs_dune.inc doesn't exist.
```
trying removing that particular line from the `dune` file in the root directory of sandmark and retry.

Step 7 - If the above steps work without any issues now we can run the executable to reproduce the segfault.
- `cd <sandmark repo location>`
- `./_build/default/benchmarks/irmin/layers.exe`

**Segfault Output**
```
Running benchmarks in benchmarks/irmin/layers.ml:
  
  { ncommits = 4096;
    ncycles = 10;
    depth = 10;
    root = "test-bench";
    clear = false;
    no_freeze = false;
    show_stats = false;
    merge_throttle = Block_writes;
    freeze_throttle = Block_writes }
  
Segmentation fault (core dumped)

```

When I run with any small argument like `_build/default/benchmarks/irmin/layers.exe -n 616`

**Expected Output**
```
Running benchmarks in benchmarks/irmin/layers.ml:
  
  { ncommits = 616;
    ncycles = 10;
    depth = 10;
    root = "test-bench";
    clear = false;
    no_freeze = false;
    show_stats = false;
    merge_throttle = Block_writes;
    freeze_throttle = Block_writes }
  
+1614953551us  application 9240 commits completed in 59.45s.
[0.006s per commit, 155 commits per second]
```

**Comment by abbysmal** [comment]
I just submitted a PR addressing this issue. (see #487)

The gist of it is that the program was segfaulting at this line:
https://github.com/ocaml-multicore/ocaml-multicore/blob/parallel_minor_gc/runtime/amd64.S#L394
The current value for the field saved in `r15` (`gc_regs_buckets`) was `0xe00000000`, leading to the segfault at this particular line.
This was due to `gc_regs_buckets` not being initialized when spinning a new systhreads.

Sorry for this mistake. The why this was not visible before is a mystery to me (?).

Thank you Shubham for looking into this. :)

**Comment by shubhamkumar13** [comment]
Thanks @Engil for the fix. I have tested this by reproducing the bug on the fixed branch and it seems to run without any segfault.
```
$ OCAMLRUNPARAM=v=0x400 ../../_build/default/benchmarks/irmin/layers.exe 
### OCaml runtime: debug mode ###
Running benchmarks in benchmarks/irmin/layers.ml:
  
  { ncommits = 4096;
    ncycles = 10;
    depth = 10;
    root = "test-bench";
    clear = false;
    no_freeze = false;
    show_stats = false;
    merge_throttle = Block_writes;
    freeze_throttle = Block_writes }
  
+1615378855us [WARNING] index_unix Semaphore merge { id=2 } was blocked for 2.359s
+1615378869us [WARNING] index_unix Semaphore merge { id=3 } was blocked for 2.74s
+1615378916us [WARNING] index_unix Semaphore clear was blocked for 1.17s
+1615379189us [WARNING] index_unix Semaphore find_instance was blocked for 1.052s
+1615379273us [WARNING] index_unix Semaphore find_instance was blocked for 1.176s
+1615379365us [WARNING] index_unix Semaphore find_instance was blocked for 1.294s
+1615379462us [WARNING] index_unix Semaphore find_instance was blocked for 1.686s
+1615379564us [WARNING] index_unix Semaphore find_instance was blocked for 1.335s
+1615379661us [WARNING] index_unix Semaphore close was blocked for 1.181s
+1615379661us  application 61440 commits completed in 813.64s.
[0.013s per commit, 76 commits per second]
allocated_words: 74567918680
minor_words: 74102480888
promoted_words: 2946346896
major_words: 3411784688
minor_collections: 282837
major_collections: 157
heap_words: 140051553
top_heap_words: 154447695
mean_space_overhead: 67.008501
```

This issue can be closed
