### ISSUE TITLE
Crash on AFL fuzzing

### ISSUE THREAD

**Issue by SumitPadhiyar** [ocamllabs/ocaml-multicore#497]
I am trying to AFL fuzz a simple program:
```ocaml
let _ = if ( read_int () mod 2) = 0 then () else failwith "false"
``` 
with `4.10.0+multicore` compiler. But it crashes with `PROGRAM ABORT : Fork server crashed with signal 11 Location : init_forkserver(), afl-fuzz.c:2230`. The backtrace from core dump is as below:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005597c3180639 in caml_raise (v=94110303735832) at fail_nat.c:63
63        if (Caml_state->c_stack == 0)
(gdb) bt
#0  0x00005597c3180639 in caml_raise (v=94110303735832) at fail_nat.c:63
#1  0x00005597c3180a30 in caml_raise_constant (tag=<optimized out>) at fail_nat.c:87
#2  caml_raise_out_of_memory () at fail_nat.c:146
#3  0x00005597c317e3c1 in caml_init_domains (minor_heap_wsz=262144) at domain.c:353
#4  0x00005597c3183ab0 in caml_init_gc () at gc_ctrl.c:301
#5  0x00005597c31803e6 in caml_startup_common (argv=0x7fffa027cdd8, pooling=pooling@entry=0) at startup_nat.c:117
#6  0x00005597c31805a8 in caml_startup_exn (argv=<optimized out>) at startup_nat.c:143
#7  caml_main (argv=<optimized out>) at startup_nat.c:148
#8  0x00005597c315f3ec in main (argc=<optimized out>, argv=<optimized out>) at main.c:44
```

Further on passing `-m none`, afl crashes with `PROGRAM ABORT : No instrumentation detected Location : perform_dry_run(), afl-fuzz.c:2908` and the corresponding backtrace is:
```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f64f9d97801 in __GI_abort () at abort.c:79
#2  0x00005637a9c6747e in caml_fatal_error (msg=msg@entry=0x5637a9c8a954 "reading from afl-fuzz") at misc.c:138
#3  0x00005637a9c7d465 in afl_read () at afl.c:72
#4  0x00005637a9c7d5a6 in caml_setup_afl (unit=<optimized out>) at afl.c:133
#5  0x00005637a9c62afb in camlTest__entry ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
Only time AFL runs is by disabling afl forkserver optimization with `AFL_NO_FORKSRV` and passing `-m none`.

**Comment by kayceesrk** [comment]
@Sudha247 @Engil @ctk21 I wondered if this failure looks similar to the ones you have been looking at recently.

**Comment by Sudha247** [comment]
Thanks for the report @SumitPadhiyar! Could you provide the steps for reproduction? Also, please check if #494 & #491 fix this issue.

**Comment by SumitPadhiyar** [comment]
Unfortunately #494 & #491 doesn't fix this issue. Steps for reproduction are as follows:
1. Compile following `test.ml` using `ocamlfind opt -afl-instrument test.ml`
```ocaml
let _ = if ( read_int () mod 2) = 0 then () else failwith "false"
``` 
2. Create a `ip` dir. Add even number in `ip/seed` file
3. fuzz with `afl-fuzz -i ip -o op/ ./a.out`. afl-fuzz will crash with `PROGRAM ABORT : Fork server crashed with signal 11`.
4. Add memory flag to afl-fuzz with `-m none` i.e `afl-fuzz -m none  -i ip -o op/ ./a.out` which changes the error to `PROGRAM ABORT : No instrumentation detected`.

**Comment by kayceesrk** [comment]
@SumitPadhiyar Do you not have to build the compiler differently to enable afl support? In particular, you'll have to use 

```
./configure --with-afl
```
to enable afl instrumentation in the target programs. I am assuming that you are building the compiler with that flag.

**Comment by SumitPadhiyar** [comment]
No, I'm not building compiler with `--with-afl` flag. I explicitly pass `-afl-instrument` to opt while compiling programs. Shouldn't this suffice for instrumentation purpose?

**Comment by Sudha247** [comment]
Passing `-afl-instrument` is sufficient in stock OCaml because `--with-afl` flag is passed by default to the compiler during installation. It's not the case with the Multicore compiler, so I think you'll have to build the compiler by passing this flag explicitly.

**Comment by SumitPadhiyar** [comment]
The above sample program doesn't crash on testing with `4.12+domains+effects` branch, but AFL is not able to detect any paths in the binary. Compiler was configured with `--with-afl`. AFL  works as intended on the program by disabling afl forkserver optimization with `AFL_NO_FORKSRV=1`.

**Comment by adharshkamath** [comment]
Is there any update on this issue? Please let me know if there's anything I can do to help

**Comment by kayceesrk** [comment]
> but AFL is not able to detect any paths in the binary ... AFL works as intended on the program by disabling afl forkserver optimization with AFL_NO_FORKSRV=1. 

@SumitPadhiyar these statements are confusing. You mention that "AFL works as intended", but you also mention AFL is not able to detect any paths. Subsequently, @adharshkamath asks if there is any update. Clearly, something is broken, but the multicore team is unsure what your expectation is.

As the multicore team is not AFL experts, it would be useful if you can help the multicore team by stating exactly 

1. the reproduction case with the arguments that you expect to run, 
2. what is expected from a correct execution, 
3. what the multicore OCaml compiler produces in this case,
4. any insights that would help the multicore team with debugging this issue.

**Comment by SumitPadhiyar** [comment]
Let me put this in proper context. AFL executes & find bugs by disabling afl forkserver optimization with `AFL_NO_FORKSRV=1`. Without disabling forkserver optimization, AFL executes but is not able to find any path in the binary & thus no bugs at all.

To answer your specific questions:
1. Reproduction case is mentioned [above](https://github.com/ocaml-multicore/ocaml-multicore/issues/497#issuecomment-803817721)
2. Expectation is to find the mentioned bug in Step 1.
3. Multicore OCaml produces a correct binary, but AFL is not able to find bugs in it
4. I suspect that this has to do with AFL instrumentation codebase, but I'm not sure.

**Comment by adharshkamath** [comment]
More details on the forkserver optimization can be found here - https://lcamtuf.blogspot.com/2014/10/fuzzing-binaries-without-execve.html 
The optimization enables AFL to save the time spent doing library initializations every time it runs the binary. To do this, AFL "pauses" the binary at the `main()` function and forks that process for every run instead of calling `execve()` every time.

More details on the instrumentation used by AFL can be found here - https://lcamtuf.coredump.cx/afl/technical_details.txt
