### ISSUE TITLE
[Copy-based, Native] Deadlock in chameneos-redux

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#51]
`chameneos-redux` benchmark intermittently deadlocks under native backend of copy-based promotion scheme. Here are the steps to recreate the bug:

```
# Assuming `native` branch is the current compiler
$ git clone https://github.com/kayceesrk/ocaml15-eff
$ cd ocaml15-eff
$ git checkout multicore
$ cd chameneos-redux
$ make chameneos-eff
$ ./chameneos-eff 1000 2
```

After a few runs, you may see that the program deadlocks. On investigation, it appears that one of the worker threads spawned goes AWOL during the execution, which blocks the main thread from running to completion.

**Comment by stedolan** [comment]
Can't reproduce this bug under move-based promotion.
