### ISSUE TITLE
Implement GC memory speed adjustment interface

### ISSUE THREAD

**Issue by ctk21** [ocamllabs/ocaml-multicore#512]
We need to implement a multicore GC solution for:
- `caml_adjust_gc_speed`
- `caml_alloc_dependent_memory`/`caml_free_dependent_memory`

An example of where `caml_adjust_gc_speed` is needed is for `base_bigstring` which is a dependency for `Core_kernel`. You can see things fail within a `4.12+domains` opam switch with `opam install base_bigstring`

**Comment by abbysmal** [comment]
Related: #460
