### ISSUE TITLE
Improve CI runs

### ISSUE THREAD

**Issue by abbysmal** [ocamllabs/ocaml-multicore#524]
Miscellaneous run settings to add to the CI matrix:
- Run multiple time specific parts of the testsuite (`parallel` and such)
- tiny minor heap runs
- `-O0` runs

**Comment by sadiqj** [comment]
Restricting the benchmarks to a single core is another good way of shaking out parallel issues.

**Comment by abbysmal** [comment]
Another idea:

We may want to introduce a wider parameter to control `num_domains` in some tests.
This would also to use as many core as available and to control a bit better the kind of codepaths we want to explore.
In some cases we want to keep a fixed number of domains to demonstrate certain specific properties, however for many things we may as well allow to spawn as many domains as possible.

**Comment by ctk21** [comment]
Closing as #528 is merged
