### ISSUE TITLE
Concurrent compacting collector

### ISSUE THREAD

**Issue by DemiMarie** [ocamllabs/ocaml-multicore#551]
Recent JVMs have support for fully concurrent GC, with no stop-the-world pauses at all.  It would be nice if OCaml could do the same, though making multicore actually work takes precedence.

**Comment by DemiMarie** [comment]
Feel free to close this as “won’t fix” if it would be too much work.

**Comment by kayceesrk** [comment]
Pauseless GC is currently not in our plans. Our current maximum pause times are not from stop-the-world sections. I'm closing this for now.
