### ISSUE TITLE
Support for ocamlopt?

### ISSUE THREAD

**Issue by bluddy** [ocamllabs/ocaml-multicore#56]
Is the current version supposed to have a native compiler? I don't get one when I try to build using `opam switch` , and then reagents seems to force a native build in the makefile, which fails.

**Comment by kayceesrk** [comment]
I just pushed an update to `ocamllabs/opam-repo-dev`. Now assuming you already have set up the remote (by `opam remote add ocamllabs -k git https://github.com/ocamllabs/opam-repo-dev`)

```
$ opam update
$ opam switch 4.02.2+multicore
```

This should install the multicore compiler with native code backend.

**Comment by bluddy** [comment]
I'm getting issues installing on OSX. Specifically,
`ld: illegal thread local variable reference to regular symbol _caml_domain_state`

This is when the line 
`../../boot/ocamlrun ../../ocamlopt -nostdlib -I ../../stdlib -shared -o unix.cmxs -I . unix.cmxa`

is run in otherlibs/unix.

**Comment by kayceesrk** [comment]
Thread local variables are a pain in OSX! This linker issue needs to be sorted out. Could you make a new issue so that we could keep track of it, and close this one? Thanks!

**Comment by kayceesrk** [comment]
Closing this issue. Opened #57.
