### ISSUE TITLE
4.12+domains+effects fails to compile CompCert, with syntax errors at the "effect" variable

### ISSUE THREAD

**Issue by ewanmellor** [ocamllabs/ocaml-multicore#569]
Building CompCert with 4.12+domains+effects fails with many errors, the first of which is a syntax error at a `let effect = `.  (Note that 4.12+domains does not fail in the same way.)

Compiler: [06d5aa0b](https://github.com/ocaml-multicore/ocaml-multicore/commit/06d5aa0bf63778de509a7eee129bb5f31508466f) (current HEAD of 4.12+domains+effects branch).
Full build log: https://multicore.ci.ocamllabs.io:8100/job/2021-06-08/043431-ci-ocluster-build-e1c556
Successful build with stock 4.12, for comparison: https://multicore.ci.ocamllabs.io:8100/job/2021-06-08/043533-ci-ocluster-build-5c25c7
Build with stock 4.12+effects which fails for different reasons, for comparison: https://multicore.ci.ocamllabs.io:8100/job/2021-06-08/043305-ci-ocluster-build-78d78a

To reproduce:

```
git clone --recursive "https://github.com/ocaml-multicore/ocaml-multicore" -b "4.12+domains+effects" && cd "ocaml-multicore" && git reset --hard 06d5aa0b
cat > Dockerfile <<'END-OF-DOCKERFILE'
FROM ocaml/opam@sha256:ed8f423a5568e86d46fa0c1895796d450b70fadd42f961afae74334c1a60a693
# Variant: debian-10-4.12+domains
USER 1000:1000
# Update opam-repository
WORKDIR /home/opam/opam-repository
RUN (git cat-file -e 161f03f0a11110be99f478b0ee1506b820e05f82 || git fetch origin master) && git reset -q --hard 161f03f0a11110be99f478b0ee1506b820e05f82 && git log --no-decorate -n1 --oneline && opam update -u
# Initialize project source
COPY --chown=1000:1000 . /src/
WORKDIR /src
# Create switch for compiler (compiler-06d5aa0b)
RUN opam switch create compiler-06d5aa0b --empty && opam repository && opam pin add -k path --inplace-build ocaml-variants.4.12.0+multicore .
# Run build
RUN opam exec -- sudo apt-get install -y libgmp-dev
RUN opam exec -- opam install coq menhir
RUN opam exec -- ./configure x86_64-linux
RUN opam exec -- make
RUN opam exec -- make test

END-OF-DOCKERFILE
docker build .
```

Example failure:

```
# File "pretyping/reductionops.ml", line 48, characters 8-14:
# 48 |     let effect = Strin
#              ^^^^^^
# Error: Syntax error
```

**Comment by ctk21** [comment]
`4.12+domains+effects` has `effect` as a keyword. Hence code which tries to use `effect` as a variable name will fail. 

The recommendation is to use `4.12+domains` to compile and run such code. 
I don't think this is

**Comment by ewanmellor** [comment]
@ctk21 So when you want to upstream the effects syntax, the plan is to tell everyone using effect as a variable that they need to change their code?

**Comment by ctk21** [comment]
So right now upstreaming fibers and effects is well in the future. The current working assumption is along that things will be proposed upstream from multicore in the following order:
- propose domains upstream (the `+domains`)
- propose fibers/continuations but have low level functions for accessing these and recreating the effect functionality
- propose fully typed effects (currently a research topic) and any (potentially breaking) syntax extensions

Right now, people should view the `+effects` branch with its breaking effect syntax as subject to future changes.

**Comment by ewanmellor** [comment]
@ctk21 OK, so how would you like to handle this from the point of view of CI?  I don't imagine CompCert (et al) are going to make changes for a far-future breaking syntax change, so these packages are never going to build.  Should we have a blocklist for them so that we don't run the +effects build for packages with known syntax incompatibilities?

**Comment by kayceesrk** [comment]
A block list seems like a good idea.

**Comment by ctk21** [comment]
> @ctk21 OK, so how would you like to handle this from the point of view of CI? I don't imagine CompCert (et al) are going to make changes for a far-future breaking syntax change, so these packages are never going to build. Should we have a blocklist for them so that we don't run the +effects build for packages with known syntax incompatibilities?

From a CI perspective, having a 'blocklist' for disabling packages with syntax incompatibilities is a good idea.

**Comment by ewanmellor** [comment]
Blocklist is now done.  Closing this as "expected behavior" otherwise.
