### ISSUE TITLE
Make extern/intern multi-thread safe and inline with upstream ocaml

### ISSUE THREAD

**Issue by ctk21** [ocamllabs/ocaml-multicore#571]
The `extern.c` / `intern.c` files have diverged from their upstream ocaml counterparts. This divergence should no longer be necessary, except that needed to make the functions multi-thread safe. 

Note that the marshalling for closures in upstream changed recently [ocaml#9649](https://github.com/ocaml/ocaml/pull/9649)

**Comment by ctk21** [comment]
Related #75

**Comment by kayceesrk** [comment]
Fixed #612.
