### ISSUE TITLE
Provide a way to indicate that a C function will not access the OCaml heap at all

### ISSUE THREAD

**Issue by DemiMarie** [ocamllabs/ocaml-multicore#60]
If [OCaml PR #652][1] or a variant thereof gets merged, there will likely be a significant number of C functions that take only C data types (pointers, ints, unboxed doubles) as arguments, and that never
- Access the OCaml heap
- Call into OCaml code

It should be possible for the compiler to emit code that allows the GC to run during such calls.

**Comment by stedolan** [comment]
This is already present, even in stock OCaml: You can allow the GC to run during a C call by wrapping it in `caml_enter_blocking_section` / `caml_leave_blocking_section`. You can also mark C functions as `[@@noalloc]` to indicate that they don't allocate on the OCaml heap, and less GC setup need be done.
