### ISSUE TITLE
caml_young_end is not a value * anymore

### ISSUE THREAD

**Issue by abbysmal** [ocamllabs/ocaml-multicore#607]
Small inconsistency we can see in CI:
`caml_young_end` is now a `char *` rather than a `value *`, causing some warnings in pre-existing code.

This can be seen in `lablgtk`: http://check.ocamllabs.io:8082/log/1624991904-364a3dc92d821c5de168ef561a9f2a79860cfafc/4.12+domains/bad/lablgtk3.3.1.1

**Comment by kayceesrk** [comment]
The inconsistency has been fixed by https://github.com/ocaml-multicore/ocaml-multicore/pull/652/.
