### ISSUE TITLE
Provide a way to allocate directly in the major heap

### ISSUE THREAD

**Issue by DemiMarie** [ocamllabs/ocaml-multicore#61]
There should be a function (of type `() -> 'a`) or other way to allocate directly in the major heap.  This is useful for data that will definitely be shared with other threads, as well as for mutable data that is read a lot (such as large arrays).  Especially in the latter case, it is quite common that performance of reads and writes are critical, while performance of allocation generally isn't.

**Comment by DemiMarie** [comment]
If the function approach is used it will need to be a compiler intrinsic.  Probably better to use dedicated syntax.

**Comment by kayceesrk** [comment]
Large arrays are already directly allocated on the major heap. This is true with vanilla OCaml as well. I have differing opinion wrt providing a primitive to allocate on the major heap. I believe that the OCaml programmer should not be exposed to the details of the GC unless it is really necessary. If we indeed add a new compiler primitive, then it is certainly a point of abuse that will lead to bad program behaviour. Implicit promotion to major heap is already fast. 

If there are indeed strong latency requirements for certain operations that mandate that certain objects be in the major heap, it is better to expose the `caml_obj_promote_to(a,b)` primitive [0], which lifts `a` upto where `b` is allocated. 

[0] https://github.com/ocamllabs/ocaml-multicore/blob/db89fbfefa668fa196fe257cec07cc3204b3c828/byterun/obj.c#L111

**Comment by DemiMarie** [comment]
A better example would be inter-thread message queues.  You _know_ that these objects will be shared, so it is better to promote them at once.

**Comment by stedolan** [comment]
Closed in favour of exposing `caml_obj_promote_to` per #36

**Comment by stedolan** [comment]
`caml_obj_promote_to` is now exposed as `Gc.promote_to` by e1f4b46f8dc0551baa558ea24540c0a5d8ba5f68
