### ISSUE TITLE
Crash running multicore binary under AFL

### ISSUE THREAD

**Issue by talex5** [ocamllabs/ocaml-multicore#611]
The `bun` package's tests pass on 4.12, but crash on 4.12+domains. Is this expected?

Building this Dockerfile:
```Dockerfile
FROM ocaml/opam:debian-ocaml-4.12
RUN opam pin -n bun "https://github.com/ocurrent/bun.git#5d280df82aa96dfef054a6f06d3ff8785af9ca85"
RUN opam install --deps-only -t bun
ENV AFL_SKIP_CPUFREQ=1 
RUN opam install -t bun

FROM ocaml/opam:debian-ocaml-4.12-domains
RUN opam pin -n bun "https://github.com/ocurrent/bun.git#5d280df82aa96dfef054a6f06d3ff8785af9ca85"
RUN opam install --deps-only -t bun
ENV AFL_SKIP_CPUFREQ=1 
RUN opam install -t bun
```

produces

```
$ docker build .
Step 1/10 : FROM ocaml/opam:debian-ocaml-4.12
...
-> installed bun.0.3.3

Step 6/10 : FROM ocaml/opam:debian-ocaml-4.12-domains
...
# [-] Whoops, the target binary crashed suddenly, before receiving any input
#     from the fuzzer!
```

Might be related to #497, where a comment says:
> Passing -afl-instrument is sufficient in stock OCaml because --with-afl flag is passed by default to the compiler during installation. It's not the case with the Multicore compiler, so I think you'll have to build the compiler by passing this flag explicitly.

If so, why is AFL off by default in multicore?

**Comment by jmid** [comment]
Hi @talex5 Can you check whether this is fixed by #731? (when running with a suitably large `-m` parameter - see #732 and #733)

> If so, why is AFL off by default in multicore?

It isn't:
```
$ ocamlopt -version
4.12.0+domains
$ cat hello.ml 
print_endline "hello world!";;
$ ocamlopt -dcmm hello.ml 2>&1 | grep afl
$ ocamlopt -afl-instrument -dcmm hello.ml 2>&1 | grep afl
   (shared_mem/86 (load_mut_imm int "caml_afl_area_ptr")
    pos/85 (xor (load_mut_imm int "caml_afl_prev_loc") 25024))
   (store int "caml_afl_prev_loc" 12512))
 (extcall "caml_setup_afl" 0 ->int)
```

AFAIU, when compiling with `-afl-instrument` you "only" get coverage guidance of the user-code (read: AFL is fuzzing the stdlib-parts blindfolded). With the `configure` option `--with-afl` coverage is also monitored for the stdlib  parts.

**Comment by talex5** [comment]
I get the same output today. I tried it using:
```
cd opam-repository/
git pull origin master
opam update
opam switch create 4.12.0+domains --repositories=multicore=git+https://github.com/ocaml-multicore/multicore-opam.git,default
eval $(opam env)
```
`ocaml --version` just says "The OCaml toplevel, version 4.12.0+domains".

**Comment by jmid** [comment]
Hm. I suspect this is because opam builds `4.12.0+domain` rather than 5.0. 
I'll try the bun build instructions from the Docker file...

**Comment by jmid** [comment]
OK. I can reproduce your error on 4.12.0+domains by running the Docker build steps:
```
opam pin -n bun "https://github.com/ocurrent/bun.git#5d280df82aa96dfef054a6f06d3ff8785af9ca85"
opam install --deps-only -t bun
ENV AFL_SKIP_CPUFREQ=1 
RUN opam install -t bun
```
If I then go to the opam build directory I can see the behaviour changes to `PROGRAM ABORT : No instrumentation detected` by cranking up the virtual memory parameter (bun does not seem to support `-m none` or `-m 513G` like afl-fuzz):
```
cd ~/.opam/4.12.0+domains/.opam-switch/build/bun.0.3.4/_build/default/test
timeout 30s ../src/bun.exe -vv -m 525000 --max-cores=2 ./short.exe
```
This was the same behaviour I observed for #731.

I then installed my local compiler repo containing the #731 patch as a local _opam switch - and ran the above again.
This still fails with `Whoops, the target binary crashed suddenly, before receiving any input from the fuzzer! 
There are several probable explanations: - The current memory limit (200 MB) is too restrictive, ...`

However, from `_opam/.opam-switch/build/bun.0.3.4/_build/default/test` the dune test now works (with enough memory):
```
$ timeout 30s ../src/bun.exe -vv -m 525000 --max-cores=2 ./short.exe
16:36.39:[EXEC:965157]['afl-gotcpu']
16:36.39:[EXEC:965158]['grep' 'more processes on ']
16:36.40:[INFO]1 available cores detected!

[...]


[*] Spinning up the fork server...
[+] All right - fork server is up.
    len = 396, map size = 1, exec speed = 190 us
[+] All test cases processed.

[+] Here are some useful stats:

    Test case count : 1 favored, 0 variable, 1 total
       Bitmap range : 1 to 1 bits (average: 1.00 bits)
        Exec timing : 190 to 190 us (average: 190 us)

[*] No -t option specified, so I'll use exec timeout of 20 ms.
[+] All set and ready to roll!
[*] Entering queue cycle 1.
[*] Fuzzing test case #0 (1 total, 0 uniq crashes found)...


+++ Testing aborted programmatically +++
[+] We're done here. Have a nice day!

16:36.40:Fuzzer 1 (pid=965163) finished
Crashes found! Take a look; copy/paste to save for reproduction:  [...]
```

Overall #731 seems to fix this. The virtual memory requirements may still bite though.
So, you have to crank up bun's `-m` parameter for multicore (see discussion in #733).

**Comment by talex5** [comment]
Thanks! I'll close this then, as #733 is tracking the issue already,
