### ISSUE TITLE
Review io.c for thread-safety and add parallel tests

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#618]
A number of thread-safety fixes have been put in `io.c` in #612. The file needs a holistic review for thread-safety. We also need tests to exercise `io.c` features in parallel.

**Comment by ctk21** [comment]
There are also `TODO` comments in `io.c` that need looking at: https://github.com/ocaml-multicore/ocaml-multicore/pull/612#discussion_r669473395

**Comment by kayceesrk** [comment]
Fixed by signal handler changes. #630, #631 and #649.
