### ISSUE TITLE
Consider non-moving generational mark-region for the shared heap

### ISSUE THREAD

**Issue by DemiMarie** [ocamllabs/ocaml-multicore#62]
One option for the shared heap is non-moving generational mark-reagion GC.  The advantage of this is that it is faster than many other non-moving algorithms (it is the basis for the "New Garbage Collector" for LuaJIT) and might be fast enough to allow directly allocating some mutable objects on the major heap.

**Comment by stedolan** [comment]
What exactly are you proposing? LuaJIT's new GC is mark-and-sweep, not mark-region, and efficient parallel incremental mark-region collectors are remarkably difficult to implement.
