### ISSUE TITLE
Str module multi domain safety

### ISSUE THREAD

**Issue by avsm** [ocamllabs/ocaml-multicore#632]
The OCaml [Str](https://ocaml.org/api/Str.html) module provides regexp support for the stdlib. While there are pure OCaml alternatives like [Re](https://github.com/ocaml/ocaml-re), the `Str` module remains heavily used in the ecosystem.

One of the difficulties of making Str Domains-safe is that the module uses global mutable state (e.g. [Str.matched_string](https://ocaml.org/api/Str.html#1_Stringmatchingandsearching)) that depends on the result of previous calls into Str.  This is already difficult to use in a concurrent setting in vanilla OCaml, but multicore OCaml can introduce new preemption points simply by spinning up a new Domain.

I'm not sure there's a quick solution to this "new Domains corrupting Str state" problem. Adding a mutex around Str isn't sufficient to prevent multiple sequential calls from interleaving.  I suspect we need to move the Str global state to be domain-local instead, which requires changes to the C bindings in otherlibs/str.

**Comment by kayceesrk** [comment]
See PR #635 which attempts to fix Str module.

**Comment by ctk21** [comment]
For `4.12+domains+effects` & `4.12+domains` #635 fixes the issue.

This is also fixed upstream in [ocaml/ocaml#10670](https://github.com/ocaml/ocaml/pull/10670)
We have picked this upstream fix up in the `5.00` branch.

**Comment by ctk21** [comment]
There is also #657 addressing the domain local point.
