### ISSUE TITLE
Fibers GCed while still alive

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#64]
This benchmark [0] in the Reagents library gets stuck as fibers seem to be GCed while still alive. The temporary fix was to incur a space leak and keep alive every fiber [1]. This seems to indicate strongly in the direction that fibers are getting GCed too early.

[0] https://github.com/ocamllabs/reagents/blob/master/test/stack_test_compose.ml
[1] https://github.com/ocamllabs/reagents/compare/avoid-thread-loss

**Comment by stedolan** [comment]
I'd like to try and reproduce this, because the fiber code was recently changed, but I'm having trouble building the test case.

**Comment by stedolan** [comment]
Is this still an issue? I can't install `kcas` at the moment.

**Comment by kayceesrk** [comment]
I can reproduce the issue. However, keeping all the continuations alive does not prevent deadlock. I suspect this might be an issue with the reagents implementation. I am going to close this issue and open a corresponding one under reagents library.
