### ISSUE TITLE
GC: Audit that we don't need any action for ocaml#10449

### ISSUE THREAD

**Issue by ctk21** [ocamllabs/ocaml-multicore#665]
Following the rebase to 5.0, it wasn't immediately clear that we needed any action to bring ocaml-multicore in line with the GC accounting into line with [ocaml#10449](https://github.com/ocaml/ocaml/pull/10449).

It would be good to know if there are any ocaml-multicore accounting issues that need fixing or if we are in line with upstream.

**Comment by sadiqj** [comment]
We have the same treatment in multicore now, so I think we're good: https://github.com/ocaml-multicore/ocaml-multicore/blob/5.00/runtime/major_gc.c#L688 (we account for the full size)
