### ISSUE TITLE
[yuasa barrier] Avoid mutator blocking on stack scanning

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#67]
Under yuasa (deletion) barrier design, the all the fiber stacks need to be marked at the start of the GC cycle. We can perform this incrementally by scanning the non-black fiber stack on context switching to it. However, this scanning operation still blocks the mutator and can add noticeable  latency for large stacks.

This proposal [0] for Golang obviates STW stack rescanning by enhancing the write barrier to take into account whether the current stack is black. This design avoids the non-incremental stack scanning in the current design by paying instead for slower write barrier. 

The main advantage with the scan-on-context-switch design is that non-concurrent OCaml code does not pay any additional cost (no need to check for colour of the current stack in the write barrier). I would think this to be important for performance backwards compatibility. The disadvantage is that context switching may incur a stack scan. This seems like a reasonable choice since we expect fewer context switches than writes. The stack scanning on context switching is only needed once per major GC cycle, that too if the stack hasn’t already been scanned by the GC.

Since the change to get new write barrier design is minimal, it would be worthwhile to implement and benchmark this scheme.

[0] https://github.com/golang/proposal/blob/master/design/17503-eliminate-rescan.md

**Comment by stedolan** [comment]
On Tue, Nov 1, 2016 at 8:53 AM, KC Sivaramakrishnan <
notifications@github.com> wrote:

> Under yuasa (deletion) barrier design, the all the fiber stacks need to be
> marked at the start of the GC cycle. We can perform this incrementally by
> scanning the non-black fiber stack on context switching to it. However,
> this scanning operation still blocks the mutator and can add noticeable
> latency for large stacks.
>
> This proposal [0,1] for Golang obviates STW stack rescanning by enhancing
> the write barrier to take into account whether the current stack is black.
> This design avoids the non-incremental stack scanning in the current design
> by paying instead for slower write barrier.
>
> The main advantage with the scan-on-context-switch design is that
> non-concurrent OCaml code does not pay any additional cost (no need to
> check for colour of the current stack in the write barrier). I would think
> this to be important for performance backwards compatibility. The
> disadvantage is that context switching may incur a stack scan. This seems
> like a reasonable choice since we expect fewer context switches than
> writes. The stack scanning on context switching is only needed once per
> major GC cycle, that too if the stack hasn’t already been scanned by the GC.
>
I agree. I'm happy with scan-on-context-switch. If latency becomes an
issue, I think doing that incrementally (or segmenting stacks) is a better
fix than complicating the write barrier.

> Since the change to get new write barrier design is minimal, it would be
> worthwhile to implement and benchmark this scheme.
>
> [0] https://github.com/golang/proposal/blob/master/design/
> 17503-eliminate-rescan.md
>
Is it really that minimal? "if current stack is grey" is not trivial in
multicore OCaml, since mark stacks are local.

Stephen

**Comment by kayceesrk** [comment]
> Is it really that minimal? "if current stack is grey" is not trivial in multicore OCaml, since mark stacks are local.

Checking whether the caml_current_stack object is grey should be trivial. Not sure I understand what this has to do with the mark stack? May be I'm missing something.

**Comment by stedolan** [comment]
On Tue, Nov 1, 2016 at 4:20 PM, KC Sivaramakrishnan <
notifications@github.com> wrote:

> Is it really that minimal? "if current stack is grey" is not trivial in
> multicore OCaml, since mark stacks are local.
>
> Checking whether the caml_current_stack object is grey should be trivial.
> Not sure I understand what this has to do with the mark stack? May be I'm
> missing something.
>
There's no easy way to check whether an object is grey in the current GC.
Objects are either UNMARKED (white) or MARKED (grey / black). The only
distinction between a grey and a black object is whether it appears in some
domain's mark stack. (This setup allows racy marking, where domains need
not synchronise to modify the mark bits)

**Comment by lpw25** [comment]
In this context I think "grey" just means whether or not the stack has been scanned. (You can think of roots/stacks as always being either grey or black, with scanning moving them from grey to black by marking their contents grey).

**Comment by kayceesrk** [comment]
Related (and subsumed by) https://github.com/ocamllabs/ocaml-multicore/issues/41.

**Comment by kayceesrk** [comment]
Fixed by #147.
