### ISSUE TITLE
Surprising performance difference from tiny code modifications

### ISSUE THREAD

**Issue by lingmar** [ocamllabs/ocaml-multicore#700]
Hi!

**Describe the issue**
I discovered some OCaml programs where tiny modifications changes the execution time of the programs considerably. I suspect the changes enable/disable some compiler optimization(s). Perhaps this is not a bug or an issue at all, but I found the runtime differences so surprising that I found it worth to report.  Moreover, the performance difference is much smaller on the default OCaml switch than on multicore.

**To reproduce**

Program 1: runtime 2.12 s
```ocaml
let rec fibonacci n =
  if n < 3 then 1
  else (fibonacci (n - 1)) + (fibonacci (n - 2))

let pmap nbrChunks f seq =
  let nbrChunks = 1 in
  if nbrChunks = 1 then List.map f seq
  else failwith "error"

let _ =
  (* Slow version *)
  List.init 1000000 (fun _ -> pmap 1 (fun x -> fibonacci x) (List.init 10 (fun _ -> 10)))
```
Program 2 (changes the last line from `fun x -> fibonacci x` to `fibonacci`: runtime 2.42 s
```ocaml
let rec fibonacci n =
  if n < 3 then 1
  else (fibonacci (n - 1)) + (fibonacci (n - 2))

let pmap nbrChunks f seq =
  let nbrChunks = 1 in
  if nbrChunks = 1 then List.map f seq
  else failwith "error"

let _ =
  (* Fast version *)
  List.init 1000000 (fun _ -> pmap 1 fibonacci (List.init 10 (fun _ -> 10)))
```
If the line `let nbrChunks = 1` is removed then the programs seem to be equally fast.

The programs are compiled with `dune` using
```
(env
  (dev
    (flags (:standard -w -a))))
(executable
  (name prog))
```

**Multicore OCaml build version**

```
$ strings _build/default/prog.exe | grep OCAML_RUNTIME_BUILD_GIT_HASH_IS                                                                                                                    lingmar@lingmar-mbp
OCAML_RUNTIME_BUILD_GIT_HASH_IS_c79158cfb
```

**Comment by kayceesrk** [comment]
I had a look at the generated code and we're not doing anything different from what stock OCaml does. I don't think there is anything for multicore devs to fix.

Moreover, these sort of differences are very much dependent on the specific version of the processor. For example, 

```bash
kc@kaveri:~/repos/ocaml-multicore/temp$ ../_install/bin/ocamlopt.opt -g -o slow.exe slow.ml
kc@kaveri:~/repos/ocaml-multicore/temp$ ../_install/bin/ocamlopt.opt -g -o fast.exe fast.ml
kc@kaveri:~/repos/ocaml-multicore/temp$ hyperfine ./slow.exe 
Benchmark #1: ./slow.exe
  Time (mean ± σ):      2.966 s ±  0.075 s    [User: 2.799 s, System: 0.167 s]
  Range (min … max):    2.892 s …  3.061 s    10 runs
 
kc@kaveri:~/repos/ocaml-multicore/temp$ hyperfine ./fast.exe 
Benchmark #1: ./fast.exe
  Time (mean ± σ):      2.847 s ±  0.074 s    [User: 2.682 s, System: 0.165 s]
  Range (min … max):    2.751 s …  2.945 s    10 runs
 
kc@kaveri:~/repos/ocaml-multicore/temp$ 
```

The fast version is faster, but not as much as the numbers that you are seeing. (I recommend `hyperfine` if you are benchmarking short running programs).

**Comment by lingmar** [comment]
Thank you for having a look! Yes, `hyperfine` is great.

Interestingly I see 14% performance difference on multicore, but only 4% difference on stock OCaml.

Out of curiosity, what could the reason for the performance difference be? I am a bit surprised already by the 4% difference for such a small code modification.

Is it worth submitting this to stock OCaml, you think?

**Comment by kayceesrk** [comment]
The additional closure allocation in the slow version due to `fun x -> fibonacci x`; eta expansion isn't free in OCaml. Looking at the code, optimisation does kick in, but not until late in the compilation pipeline. It may be worth asking on OCaml discuss about this.
