### ISSUE TITLE
Update base-domains package for 5.00 branch

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#728]
With the 5.00 branch, I'm unable to create a local opam switch.

```bash
$ opam pin add -k path --inplace-build ocaml-variants.4.14.0+domains .
[NOTE] Package ocaml-variants is already pinned to file:///home/kc/repos/ocaml-multicore (version 4.14.0+domains).
[ocaml-variants.4.14.0+domains] synchronised from file:///home/kc/repos/ocaml-multicore
ocaml-variants is now pinned to file:///home/kc/repos/ocaml-multicore (version 4.14.0+domains)

The following dependencies couldn't be met:
  - ocaml-variants → base-domains → ocaml-variants (= 4.12.0+domains+effects & = 4.12.0+domains & = 4.10.0+multicore &
    = 4.10.0+multicore+no-effect-syntax & = 4.06.1+multicore)
      no matching version

[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

It looks like the `base-domains` package needs to be updated to include `4.14.0+domains`. Is that right @kit-ty-kate?

**Comment by kit-ty-kate** [comment]
> It looks like the `base-domains` package needs to be updated to include `4.14.0+domains`. Is that right @kit-ty-kate?

Yes indeed, this is what i did in my fork of multicore-opam for opam-health-check, but it's worth doing it in opam-repository anyway so I opened https://github.com/ocaml/opam-repository/pull/19900

**Comment by kit-ty-kate** [comment]
This is now fixed. Could you confirm?

**Comment by kayceesrk** [comment]
Works. Thank you.
