### ISSUE TITLE
Benchmark suite for multicore programs

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#74]
Given that we are building a multicore compiler, we need to (slowly) build a suite of multicore programs. Primarily to benchmark the programs.

**Comment by dbuenzli** [comment]
If you don't already know about it there is this https://github.com/OCamlPro/operf-macro

**Comment by kayceesrk** [comment]
Great. Didn't know operf-macro had macro benchmarks as well. I haven't yet looked at what the benchmarks are. But we need to parallelize them. It would be useful to collect a set of potential benchmarks under this issue that would benefit from parallelization and work towards parallelizing them.

**Comment by dbuenzli** [comment]
In fact I was rather thinking about reusing the infrastructure.

**Comment by kayceesrk** [comment]
Definitely. Now that I think about it, I'd used operf-macro for benchmarking effect handlers. The infrastructure is pretty good. But I should say the use of the term "macro benchmarks" for many programs in the benchmark suite is very generous.

**Comment by kayceesrk** [comment]
Closing this. See http://ocamllabs.io/multicore.
