### ISSUE TITLE
What is the expected interaction between `Lazy` and effect handlers?

### ISSUE THREAD

**Issue by gasche** [ocamllabs/ocaml-multicore#758]
Under both Sequential and Multicore OCaml, if forcing a lazy thunk raises an exception, then this exception is recorded as the "result" of forcing, and immediately re-raised on any subsequent force.

What is the expected behavior of lazy thunks if an effect, instead of an exception, is raised?

In particular, do exceptions-encoded-as-effects behave in the same way as native exceptions? (That sounds like a desirable property.)

My expectation would be that:
- if the effect continuation is "discarded" by its handler, then this effect is recorded as the effect of forcing the thunk
- if the effect continuation is "continued" by its handler, we continue within the forcing logic so no result is recorded for the thunk yet

Is this a sensible specification? Is it possible to implement it?

(cc @lpw25 @stedolan)

**Comment by kayceesrk** [comment]
Is this the semantics you are looking for?

```ocaml
open EffectHandlers
open EffectHandlers.Deep

type _ eff += E : int eff

let l1 = lazy (perform E + perform E)

let v =
  try_with Lazy.force l1
  { effc = fun (type a) (e : a eff) ->
      match e with
      | E -> Some (fun (k : (a,_) continuation) -> continue k 1)
      | _ -> None }

let _ = assert (v = 2)


let l2 = lazy (perform E)

let v =
  match_with Lazy.force l2
  { retc = (fun x -> x);
    exnc = (fun e -> 0);
    effc = fun (type a) (e : a eff) ->
      match e with
      | E -> Some (fun (k : (a,_) continuation) -> discontinue k Exit)
      | _ -> None }

let _ =
  assert (v = 0);
  try Lazy.force l2 with Exit -> 0
```

In particular, 

> then this effect is recorded as the effect of forcing the thunk

what does "effect" mean here? Since we discard the continuation (using `discontinue`), the lazy computation raises the exception, which is recorded in the lazy value.

**Comment by gasche** [comment]
Aha! I had forgotten that discontinuation is handled by raising an exception from within the fiber. So you get exactly the semantics I would have expected, without any explicit support for effect. This is great, thanks.
