### ISSUE TITLE
Question about schedulers

### ISSUE THREAD

**Issue by bluddy** [ocamllabs/ocaml-multicore#77]
OK, so here's a concern I've had since the day the in-language schedulers were announced: the scheduler is a critical piece of code, right? You really want it to be as efficient as possible, and OCaml has non-trivial overheads. So I envision a company like Jane Street realizing that to maximize their performance, they need to use a custom C-based scheduler. They'd be essentially enhancing the runtime with their own scheduler, and to get maximum performance from OCaml, you'd have to compile against this additional bit of C code. So even though we're working to move the scheduler into the user code, it'll de-facto be a part of the non-standard runtime. Is this something we want to avoid? Would it make sense to bundle standard schedulers with the compiler -- is this something that's planned?

**Comment by lpw25** [comment]
To me this seems a complete non-issue. Neither `lwt` nor `async` write their schedulers in C. Why would they? I suspect you are dramatically under-estimating OCaml's performance. There is almost certainly more performance to be gained by being able to customise a scheduler to your particular program than from switching its implementation to C.

Besides if people want to implement them in C then so what, plenty of OCaml libraries use C stubs for things and everyone is aware of the trade-offs of doing so.
