### ISSUE TITLE
Backport PR #701 to 4.12

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#782]
https://github.com/ocaml-multicore/ocaml-multicore/pull/701 needs to be backported to `4.12+domains+effects` and `4.12+domains`. 

CC @paracetamolo.

**Comment by paracetamolo** [comment]
We were having a weird behavior in Alcotest where some tests were actually run but not included in the printed list of tests. After this fix was backported everything works fine, just needed to rebuild the opam switch. Thanks for the prompt fix!
