### ISSUE TITLE
Caml_state for domains should not use mmap

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#796]
Currently, the `Caml_state` for each domain is allocated using a complicated dance of mmap reservation, commit and decommit. See https://github.com/ocaml-multicore/ocaml-multicore/blob/5.00/runtime/domain.c#L500-L501, and other uses of `tls_area`. 

This is a vestige of the earlier concurrent minor GC, where we used the minor heap allocation pointer to identify the Caml_state area which was located adjacent to the minor heap area of a domain. This was made unnecessary ever since we started using a dedicated register (`r14` on amd64) to point to the `Caml_state`. No longer is the `Caml_state` located adjacent to the minor heap area. 

Hence, a plain old `malloc` at the domain creation time is sufficient for `Caml_state` management. This would simplify `Caml_state` management significantly.

**Comment by gadmm** [comment]
On this topic, can there be an impact of aligning Caml_state to cachelines? I had the impression that you were grouping the most frequently used variables at the beginning of the array for cache locality purposes.

**Comment by kayceesrk** [comment]
>  I had the impression that you were grouping the most frequently used variables at the beginning of the array for cache locality purposes.

We haven't measured the impact of this. Perhaps we can do aligned malloc through `caml_stat_alloc_aligned` for this one with the required alignment. I'm not an expert on this, but I assume that the alignment should be the same as the cache line size? Does OCaml expose cache line size through Sys module: https://stackoverflow.com/questions/794632/programmatically-get-the-cache-line-size.

**Comment by abbysmal** [comment]
I am currently working on addressing this issue.

I will follow up with a PR and provide benchmarks along the way.

**Comment by gadmm** [comment]
* Stay clear from `caml_stat_alloc_aligned` as it does not do what you want (the documentation is unclear: it always aligns to page size; the `modulo` argument denotes an offset).
* Getting the actual cacheline size is probably overkill, you could go for a common value (64 bytes)

If you want to try, you can start with posix_memalign to see if it is worth it before investigating further.

**Comment by xavierleroy** [comment]
> Stay clear from caml_stat_alloc_aligned

Actually, this function is no longer used in the 5.0 runtime system (it was very much related to the use of a page table), so it could probably be removed.

**Comment by dra27** [comment]
This can be closed.
