### ISSUE TITLE
Unify GC interrupt and signals triggering mechanisms

### ISSUE THREAD

**Issue by sadiqj** [ocamllabs/ocaml-multicore#806]
Copied from the comment on #790 so as it's not lost:

I'm still not 100% satisfied because caml_check_pending_actions can return false when there is actually a pending action to do (in that there's a signal to process, where the signal handler records just before a store to young_limit). That only leads to delayed delivery of a signal though.

The interaction between signals and GC interrupts needs to be reworked. Right now they feel like two independent mechanisms. The replumbing that will be required to support #791 is probably the best place to do it.

**Comment by gadmm** [comment]
As said in the other issue, some work has been done to clarify the situation regarding asynchronous actions in trunk in parallel with multicore. I did not look too closely at the current situation in the multicore branch, but at a first sight it would be nice to take inspiration/start from the treatment of pending_actions in pre-multicore trunk to avoid losing this clarification/simplification.

On the same topic, programmers of long-running C functions that hold the runtime lock are advised to regularly check for pending signals (e.g. Coq's VM). (I think it's already in the FFI manual.) It could be nice to clarify in the manual that this is also needed to avoid letting other domains wait in case of a pending GC interrupt.

**Comment by gadmm** [comment]
Fixed at #11057 and others
