### ISSUE TITLE
Filter-tree to normalise email address from commiters

### ISSUE THREAD

**Issue by sadiqj** [ocamllabs/ocaml-multicore#816]
It seems that Shubham (@shubhamkumar13 ), Enguerrand (@Engil ) and I have inconsistent names/emails amongst the commits on the Multicore PR to upstream. We should fix this before merging by doing a filter-tree.

**Comment by sadiqj** [comment]
I have a branch that has been filtered and normalises Engil, Shubham, Stephen and myself: https://github.com/sadiqj/ocaml/tree/multicore-pr

**Comment by gasche** [comment]
Note: upstream OCaml has a `.mailmap` file that normalizes committer identities in the standard git way (and keeps a little extra information). It may not be necessary to rewrite history if the latter is more work.

**Comment by sadiqj** [comment]
Annoyingly github doesn't support `.mailmap` at the moment https://github.community/t/how-to-get-mailmap-to-work-and-record-contributions-in-relevant-users-profile/121285

**Comment by ctk21** [comment]
This is done, closing it out.
