### ISSUE TITLE
Signal stack is freed, but isn't reset.

### ISSUE THREAD

**Issue by azewierzejew** [ocamllabs/ocaml-multicore#838]
In OCaml 5 the signal stack is now allocated in the static pool.
That means it's freed when `caml_shutdown` is called after `caml_startup_pooled`.
But the stack for the main thread is never reset meaning any following signals with `SA_ONSTACK` will run with freed memory as the stack.

Also `caml_init_signal_handling` adds `SA_ONSTACK` to `SIGPROF` handler which isn't reset in `caml_shutdown`.

Meaning that if user defines any handler for `SIGPROF` or handler for any signal with `SA_ONSTACK` then there is possibility of this error.

Here is the example:
```c
#include <caml/callback.h>
#include <signal.h>

void handler(int i) {
  stack_t ss;
  sigaltstack(NULL, &ss);
  // Stack is the same as in main, but SA_ONSTACK is set meaning we are ON the
  // alternative stack currently.
  printf("%p %zu %d\n", ss.ss_sp, ss.ss_size, ss.ss_flags); // Ignore signal safety.
}

int main(int argc, char **argv) {
  signal(SIGPROF, handler);

  caml_startup_pooled(argv);

  caml_shutdown();

  stack_t ss;
  sigaltstack(NULL, &ss);

  printf("%p %zu %d\n", ss.ss_sp, ss.ss_size, ss.ss_flags);
  // Following assignment shows error in valgrind as the memory was freed.
  *(char *)ss.ss_sp = 'a';

  raise(SIGPROF);
}
```

**Comment by kayceesrk** [comment]
Hi @azewierzejew, this repository is no longer actively maintained. The development has moved to https://github.com/ocaml/ocaml. I see that you have already made a PR there. It would be best to move this issue to OCaml github repo if relevant there.
