### ISSUE TITLE
Appropriate exception pointer register for domain local variables

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#85]
The domain local variables are located at the end of minor heap area of each domain. This area is obtained by bit twiddling the allocation pointer [0]. While this is a reasonable solution, the solution depends on the minor heap being aligned to block boundaries [1]. This makes the solution not easily portable to vanilla OCaml (which would benefit from the simplicity of such a single structure of globals compared to the sprinkling of global variables in the current vanilla runtime). Hence, it is desirable to remove this dependence.

The idea is to appropriate the exception pointer register (r14 on amd64) to point to the globals area, and move the exception pointer (offset, in the case of multicore) to the global structure.

[0] https://github.com/ocamllabs/ocaml-multicore/blob/master/asmrun/amd64.S#L100-L102
[1] https://github.com/ocamllabs/ocaml-multicore/blob/master/byterun/caml/config.h#L146-L153

**Comment by lpw25** [comment]
Is the idea to do this in the short-term to make it easier to merge some things upstream, and then switch back to the heap pointer version later?

Because in the long run it seems a shame to reserve two registers with essentially the same data in them.

**Comment by kayceesrk** [comment]
>  it seems a shame to reserve two registers with essentially the same data in them.

Not sure I understand this. In the proposed model, r14 refers to the globals area and r15 is still the allocation pointer. Exception pointer is moved to the globals area. We steal the same number of registers. 

@stedolan seemed to indicate that he wants migrate to this solution in the long term.

**Comment by lpw25** [comment]
> r14 refers to the globals area and r15 is still the allocation pointer.

But r14's value will always be equal to `r15 & MASK`.

> We steal the same number of registers.

Sure, but we could easily steal one fewer than now and have more registers available for ordinary code.

**Comment by kayceesrk** [comment]
Good point. I'd been imagining that once we appropriate r14 for globals, we'd move the globals area to a separate malloc'ed one, not at the end of minor heap anymore. But you make a good observation that there is no need to move the globals from the end of minor heap area. So as a move towards upstreaming, 

1. In vanilla OCaml, appropriate r14 for globals, with globals allocated using malloc. r15 remains allocation pointer and exception pointer moved to globals. This is necessary since minor heap in vanilla OCaml is not suitably aligned. Update multicore to also adopt this scheme to make the merge easier.
2. Once multicore is upstreamed, move globals to end of minor heap area. In this case, we can free up r14 for ordinary code and access globals through` r15 & MASK`.

**Comment by kayceesrk** [comment]
Done: https://github.com/ocamllabs/ocaml-multicore/pull/215.
