### ISSUE TITLE
Implement `Domain.join` primitive

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#89]
The current domain interface [0] only provides facility for domain creation. The domains asynchronously run to completion. A useful primitive would be to wait on the domain to run to completion. The expected semantics is that `Domain.join d` blocks the calling domain until the domain `d` runs to completion. Calling `Domain.join d` on a completed domain returns immediately. The expected interface is:

```ocaml
module type Domain = sig
  type t 
  (** The type of domain. *)

  val spawn : (unit -> unit) -> t
  (** Spawn a new domain that runs in parallel with the current domain. *)

  val join : t -> unit
  (** [join d] blocks until domain [d] runs to completion. If [d] has already 
      completed, then [join d] returns immediately. *)

  val self : unit -> int
  (** Return the current domain's id. *)
end
```

[0] https://github.com/ocamllabs/ocaml-multicore/blob/master/stdlib/domain.mli

**Comment by dbuenzli** [comment]
Can `spawn` fail ? If that is the case do expect that to be a recoverable failure or rather something like `Out_of_memory` ?

**Comment by kayceesrk** [comment]
`Spawn` can fail either because the underlying system thread creation has failed or the number of domains has exceeded the maximum number of domains. In both cases, they should be treated as recoverable errors.

Does `Thread.create` throw an exception if the pthread creation fails?

**Comment by dbuenzli** [comment]
> Does Thread.create throw an exception if the pthread creation fails?

I had a look at the implementation and it seems `Sys_error` will be raised.

**Comment by kayceesrk** [comment]
Thanks @dbuenzli ! Not sure if `Sys_error` or some other exception is the right solution, but `spawn` errors are certainly recoverable errors.
