### ISSUE TITLE
Implement stubs for finalizers which don't terminate the program

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#92]
Currently, `caml_final_register` and `caml_final_release` raise exception [0]. Implement stubs that do not raise an exception. A reasonable behaviour for the initial version might just be to ignore the finalizer since OCaml does not ensure that the finalizers are always run. 

[0] https://github.com/ocamllabs/ocaml-multicore/blob/master/byterun/finalise.c

**Comment by kayceesrk** [comment]
Related to #88

**Comment by stedolan** [comment]
Is this fixed now?

**Comment by kayceesrk** [comment]
Yep. finalisers are implemented now.
