### ISSUE TITLE
Port ctypes to support the new C API

### ISSUE THREAD

**Issue by kayceesrk** [ocamllabs/ocaml-multicore#97]
Ctypes: https://github.com/ocamllabs/ocaml-ctypes

*(details to be filled in)*

**Comment by yallop** [comment]
See here:
    https://github.com/yallop/ocaml-ctypes/tree/multicore-api

It was done rather quickly, and may need more care, but it builds and passes tests with https://github.com/ocaml/ocaml/pull/1003

**Comment by kayceesrk** [comment]
Excellent @yallop 👍 . CC @stedolan.
